//! Vocabulary registry - builds Runtime with all words
//!
//! This module registers all DSL vocabulary words with their metadata
//! for both execution and RAG context building.

use crate::forth_engine::runtime::{Runtime, WordEntry};
use crate::forth_engine::words;

/// Create the standard DSL runtime with all vocabulary
pub fn create_standard_runtime() -> Runtime {
    Runtime::new(vec![
        // ============ CASE Domain ============
        WordEntry {
            name: "case.create",
            domain: "case",
            func: words::case_create,
            signature: ":case-id STRING :case-type STRING",
            description: "Create a new case for onboarding",
            examples: &[r#"(case.create :case-id "CASE-001" :case-type "ONBOARDING")"#],
        },
        WordEntry {
            name: "case.update",
            domain: "case",
            func: words::case_update,
            signature: ":case-id STRING",
            description: "Update an existing case",
            examples: &[r#"(case.update :case-id "CASE-001")"#],
        },
        WordEntry {
            name: "case.validate",
            domain: "case",
            func: words::case_validate,
            signature: ":case-id STRING",
            description: "Validate a case",
            examples: &[r#"(case.validate :case-id "CASE-001")"#],
        },
        WordEntry {
            name: "case.approve",
            domain: "case",
            func: words::case_approve,
            signature: ":case-id STRING",
            description: "Approve a case",
            examples: &[r#"(case.approve :case-id "CASE-001")"#],
        },
        WordEntry {
            name: "case.close",
            domain: "case",
            func: words::case_close,
            signature: ":case-id STRING",
            description: "Close a case",
            examples: &[r#"(case.close :case-id "CASE-001")"#],
        },
        // ============ ENTITY Domain ============
        WordEntry {
            name: "entity.register",
            domain: "entity",
            func: words::entity_register,
            signature: ":entity-id STRING :entity-type STRING",
            description: "Register a new entity",
            examples: &[r#"(entity.register :entity-id "ENT-001" :entity-type "CORP")"#],
        },
        WordEntry {
            name: "entity.classify",
            domain: "entity",
            func: words::entity_classify,
            signature: ":entity-id STRING",
            description: "Classify an entity",
            examples: &[r#"(entity.classify :entity-id "ENT-001")"#],
        },
        WordEntry {
            name: "entity.link",
            domain: "entity",
            func: words::entity_link,
            signature: ":entity-id STRING :target-id STRING",
            description: "Link two entities",
            examples: &[r#"(entity.link :entity-id "ENT-001" :target-id "ENT-002")"#],
        },
        WordEntry {
            name: "identity.verify",
            domain: "entity",
            func: words::identity_verify,
            signature: ":entity-id STRING",
            description: "Verify an entity's identity",
            examples: &[r#"(identity.verify :entity-id "ENT-001")"#],
        },
        WordEntry {
            name: "identity.attest",
            domain: "entity",
            func: words::identity_attest,
            signature: ":entity-id STRING",
            description: "Attest an entity's identity",
            examples: &[r#"(identity.attest :entity-id "ENT-001")"#],
        },
        // ============ PRODUCTS Domain ============
        WordEntry {
            name: "products.add",
            domain: "products",
            func: words::products_add,
            signature: ":case-id STRING :product-type STRING",
            description: "Add a product to a case",
            examples: &[r#"(products.add :case-id "CASE-001" :product-type "CUSTODY")"#],
        },
        WordEntry {
            name: "products.configure",
            domain: "products",
            func: words::products_configure,
            signature: ":product-id STRING :config STRING",
            description: "Configure a product",
            examples: &[r#"(products.configure :product-id "PROD-001" :config "{}")"#],
        },
        WordEntry {
            name: "services.discover",
            domain: "services",
            func: words::services_discover,
            signature: ":case-id STRING",
            description: "Discover available services for a case",
            examples: &[r#"(services.discover :case-id "CASE-001")"#],
        },
        WordEntry {
            name: "services.provision",
            domain: "services",
            func: words::services_provision,
            signature: ":service-id STRING :config STRING",
            description: "Provision a service",
            examples: &[r#"(services.provision :service-id "SVC-001" :config "{}")"#],
        },
        WordEntry {
            name: "services.activate",
            domain: "services",
            func: words::services_activate,
            signature: ":service-id STRING",
            description: "Activate a service",
            examples: &[r#"(services.activate :service-id "SVC-001")"#],
        },
        // ============ KYC Domain ============
        WordEntry {
            name: "kyc.start",
            domain: "kyc",
            func: words::kyc_start,
            signature: ":entity-id STRING",
            description: "Start KYC process for an entity",
            examples: &[r#"(kyc.start :entity-id "ENT-001")"#],
        },
        WordEntry {
            name: "kyc.collect",
            domain: "kyc",
            func: words::kyc_collect,
            signature: ":case-id STRING :collection-type STRING",
            description: "Collect KYC data",
            examples: &[r#"(kyc.collect :case-id "CASE-001" :collection-type "ENHANCED")"#],
        },
        WordEntry {
            name: "kyc.verify",
            domain: "kyc",
            func: words::kyc_verify,
            signature: ":entity-id STRING",
            description: "Verify KYC for an entity",
            examples: &[r#"(kyc.verify :entity-id "ENT-001")"#],
        },
        WordEntry {
            name: "kyc.assess",
            domain: "kyc",
            func: words::kyc_assess,
            signature: ":entity-id STRING",
            description: "Assess KYC risk for an entity",
            examples: &[r#"(kyc.assess :entity-id "ENT-001")"#],
        },
        WordEntry {
            name: "compliance.screen",
            domain: "compliance",
            func: words::compliance_screen,
            signature: ":entity-id STRING",
            description: "Screen an entity for compliance",
            examples: &[r#"(compliance.screen :entity-id "ENT-001")"#],
        },
        WordEntry {
            name: "compliance.monitor",
            domain: "compliance",
            func: words::compliance_monitor,
            signature: ":entity-id STRING",
            description: "Monitor an entity for compliance",
            examples: &[r#"(compliance.monitor :entity-id "ENT-001")"#],
        },
        // ============ UBO Domain ============
        WordEntry {
            name: "ubo.collect-entity-data",
            domain: "ubo",
            func: words::ubo_collect_entity_data,
            signature: ":entity-id STRING",
            description: "Collect entity data for UBO analysis",
            examples: &[r#"(ubo.collect-entity-data :entity-id "ENT-001")"#],
        },
        WordEntry {
            name: "ubo.get-ownership-structure",
            domain: "ubo",
            func: words::ubo_get_ownership_structure,
            signature: ":entity-id STRING",
            description: "Get ownership structure for an entity",
            examples: &[r#"(ubo.get-ownership-structure :entity-id "ENT-001")"#],
        },
        WordEntry {
            name: "ubo.resolve-ubos",
            domain: "ubo",
            func: words::ubo_resolve_ubos,
            signature: ":entity-id STRING",
            description: "Resolve ultimate beneficial owners",
            examples: &[r#"(ubo.resolve-ubos :entity-id "ENT-001")"#],
        },
        WordEntry {
            name: "ubo.calculate-indirect-ownership",
            domain: "ubo",
            func: words::ubo_calculate_indirect_ownership,
            signature: ":entity-id STRING",
            description: "Calculate indirect ownership percentages",
            examples: &[r#"(ubo.calculate-indirect-ownership :entity-id "ENT-001")"#],
        },
        // ============ DOCUMENT Domain ============
        WordEntry {
            name: "document.catalog",
            domain: "document",
            func: words::document_catalog,
            signature: ":doc-id STRING :doc-type STRING",
            description: "Catalog a document for processing",
            examples: &[r#"(document.catalog :doc-id "DOC-001" :doc-type "UK-PASSPORT")"#],
        },
        WordEntry {
            name: "document.verify",
            domain: "document",
            func: words::document_verify,
            signature: ":doc-id STRING",
            description: "Verify a document",
            examples: &[r#"(document.verify :doc-id "DOC-001")"#],
        },
        WordEntry {
            name: "document.extract",
            domain: "document",
            func: words::document_extract,
            signature: ":doc-id STRING :attr-id STRING?",
            description: "Extract data from a document",
            examples: &[r#"(document.extract :doc-id "DOC-001")"#],
        },
        WordEntry {
            name: "document.link",
            domain: "document",
            func: words::document_link,
            signature: ":doc-id STRING :entity-id STRING",
            description: "Link a document to an entity",
            examples: &[r#"(document.link :doc-id "DOC-001" :entity-id "ENT-001")"#],
        },
        WordEntry {
            name: "document.link-to-cbu",
            domain: "document",
            func: words::document_link_to_cbu,
            signature: ":cbu-id STRING :document-id STRING :relationship-type STRING",
            description: "Link a document to a CBU",
            examples: &[
                r#"(document.link-to-cbu :cbu-id "CBU-001" :document-id "DOC-001" :relationship-type "PRIMARY")"#,
            ],
        },
        WordEntry {
            name: "document.extract-attributes",
            domain: "document",
            func: words::document_extract_attributes,
            signature: ":document-id STRING :document-type STRING",
            description: "Extract attributes from a document",
            examples: &[
                r#"(document.extract-attributes :document-id "DOC-001" :document-type "UK-PASSPORT")"#,
            ],
        },
        WordEntry {
            name: "document.require",
            domain: "document",
            func: words::document_require,
            signature: "@attr{UUID}",
            description: "Require a document attribute",
            examples: &[r#"(document.require @attr{uuid})"#],
        },
        // ============ CORE/ATTRIBUTE Domain ============
        WordEntry {
            name: "require-attribute",
            domain: "core",
            func: words::require_attribute,
            signature: "@attr{UUID}",
            description: "Require an attribute reference",
            examples: &[r#"(require-attribute @attr{uuid})"#],
        },
        WordEntry {
            name: "set-attribute",
            domain: "core",
            func: words::set_attribute,
            signature: "@attr{UUID} VALUE",
            description: "Set an attribute value",
            examples: &[r#"(set-attribute @attr{uuid} "value")"#],
        },
        WordEntry {
            name: "attr.require",
            domain: "attr",
            func: words::attr_require,
            signature: ":attr-id STRING",
            description: "Require an attribute",
            examples: &[r#"(attr.require :attr-id "KYC.LEI")"#],
        },
        WordEntry {
            name: "attr.set",
            domain: "attr",
            func: words::attr_set,
            signature: ":attr-id STRING :value STRING",
            description: "Set an attribute value",
            examples: &[r#"(attr.set :attr-id "KYC.LEI" :value "5493001KJTIIGC8Y1R12")"#],
        },
        WordEntry {
            name: "attr.validate",
            domain: "attr",
            func: words::attr_validate,
            signature: ":attr-id STRING :value STRING",
            description: "Validate an attribute value",
            examples: &[r#"(attr.validate :attr-id "KYC.LEI" :value "5493001KJTIIGC8Y1R12")"#],
        },
        // ============ CBU Domain ============
        WordEntry {
            name: "cbu.create",
            domain: "cbu",
            func: words::cbu_create,
            signature: ":cbu-name STRING :client-type STRING? :jurisdiction STRING? :nature-purpose STRING? :description STRING?",
            description: "Create a new Client Business Unit",
            examples: &[
                r#"(cbu.create :cbu-name "AcmeFund" :client-type "HEDGE_FUND" :jurisdiction "GB")"#,
            ],
        },
        WordEntry {
            name: "cbu.read",
            domain: "cbu",
            func: words::cbu_read,
            signature: ":cbu-id UUID",
            description: "Read a CBU by ID",
            examples: &[r#"(cbu.read :cbu-id "550e8400-e29b-41d4-a716-446655440000")"#],
        },
        WordEntry {
            name: "cbu.update",
            domain: "cbu",
            func: words::cbu_update,
            signature: ":cbu-id UUID :name STRING? :status STRING?",
            description: "Update a CBU",
            examples: &[r#"(cbu.update :cbu-id "..." :name "NewName")"#],
        },
        WordEntry {
            name: "cbu.delete",
            domain: "cbu",
            func: words::cbu_delete,
            signature: ":cbu-id UUID",
            description: "Delete a CBU",
            examples: &[r#"(cbu.delete :cbu-id "...")"#],
        },
        WordEntry {
            name: "cbu.list",
            domain: "cbu",
            func: words::cbu_list,
            signature: ":filter STRING?",
            description: "List CBUs with optional filter",
            examples: &[r#"(cbu.list :filter "status:ACTIVE")"#],
        },
        WordEntry {
            name: "cbu.attach-entity",
            domain: "cbu",
            func: words::cbu_attach_entity,
            signature: ":cbu-id UUID :entity-id UUID :role STRING :ownership-percent DECIMAL?",
            description: "Attach an existing entity to a CBU with a role",
            examples: &[
                r#"(cbu.attach-entity :cbu-id @cbu :entity-id @company :role "InvestmentManager")"#,
                r#"(cbu.attach-entity :cbu-id @cbu :entity-id @person :role "BeneficialOwner" :ownership-percent 25.0)"#,
            ],
        },
        WordEntry {
            name: "cbu.attach-proper-person",
            domain: "cbu",
            func: words::cbu_attach_proper_person,
            signature: ":person-name STRING :role STRING",
            description: "Attach a proper person to a CBU",
            examples: &[r#"(cbu.attach-proper-person :person-name "John Doe" :role "DIRECTOR")"#],
        },
        WordEntry {
            name: "cbu.finalize",
            domain: "cbu",
            func: words::cbu_finalize,
            signature: ":cbu-id UUID :status STRING",
            description: "Finalize a CBU with a status",
            examples: &[r#"(cbu.finalize :cbu-id "..." :status "ACTIVE")"#],
        },
        // ============ CRUD Domain ============
        WordEntry {
            name: "crud.begin",
            domain: "crud",
            func: words::crud_begin,
            signature: ":operation-type STRING :asset-type STRING",
            description: "Begin a CRUD operation",
            examples: &[r#"(crud.begin :operation-type "CREATE" :asset-type "CBU")"#],
        },
        WordEntry {
            name: "crud.commit",
            domain: "crud",
            func: words::crud_commit,
            signature: ":entity-table STRING :ai-instruction STRING :ai-provider STRING",
            description: "Commit a CRUD operation",
            examples: &[
                r#"(crud.commit :entity-table "cbus" :ai-instruction "Create test CBU" :ai-provider "OPENAI")"#,
            ],
        },
        // ============ TAXONOMY: Product Domain ============
        WordEntry {
            name: "product.create",
            domain: "product",
            func: words::product_create,
            signature: ":product-code STRING :name STRING :description STRING? :category STRING? :status STRING?",
            description: "Create a new product",
            examples: &[
                r#"(product.create :product-code "CUSTODY" :name "Custody Services" :category "ASSET_SERVICES")"#,
            ],
        },
        WordEntry {
            name: "product.read",
            domain: "product",
            func: words::product_read,
            signature: ":product-id UUID | :product-code STRING",
            description: "Read a product",
            examples: &[r#"(product.read :product-code "CUSTODY")"#],
        },
        WordEntry {
            name: "product.update",
            domain: "product",
            func: words::product_update,
            signature: ":product-id UUID :name STRING? :status STRING?",
            description: "Update a product",
            examples: &[r#"(product.update :product-id "..." :status "ACTIVE")"#],
        },
        WordEntry {
            name: "product.delete",
            domain: "product",
            func: words::product_delete,
            signature: ":product-id UUID",
            description: "Delete a product",
            examples: &[r#"(product.delete :product-id "...")"#],
        },
        // ============ TAXONOMY: Service Domain ============
        WordEntry {
            name: "service.create",
            domain: "service",
            func: words::service_create,
            signature: ":service-code STRING :name STRING :description STRING?",
            description: "Create a new service",
            examples: &[r#"(service.create :service-code "KYC" :name "KYC Service")"#],
        },
        WordEntry {
            name: "service.read",
            domain: "service",
            func: words::service_read,
            signature: ":service-id UUID | :service-code STRING",
            description: "Read a service",
            examples: &[r#"(service.read :service-code "KYC")"#],
        },
        WordEntry {
            name: "service.update",
            domain: "service",
            func: words::service_update,
            signature: ":service-id UUID :name STRING? :status STRING?",
            description: "Update a service",
            examples: &[r#"(service.update :service-id "..." :status "ACTIVE")"#],
        },
        WordEntry {
            name: "service.delete",
            domain: "service",
            func: words::service_delete,
            signature: ":service-id UUID",
            description: "Delete a service",
            examples: &[r#"(service.delete :service-id "...")"#],
        },
        WordEntry {
            name: "service.link-product",
            domain: "service",
            func: words::service_link_product,
            signature: ":service-id UUID :product-id UUID :config STRING?",
            description: "Link a service to a product",
            examples: &[r#"(service.link-product :service-id "..." :product-id "...")"#],
        },
        // ============ TAXONOMY: Lifecycle Resource Domain ============
        WordEntry {
            name: "lifecycle-resource.create",
            domain: "lifecycle-resource",
            func: words::lifecycle_resource_create,
            signature: ":resource-code STRING :name STRING :resource-type STRING :description STRING?",
            description: "Create a lifecycle resource",
            examples: &[
                r#"(lifecycle-resource.create :resource-code "DOC-CHECK" :name "Document Check" :resource-type "VALIDATION")"#,
            ],
        },
        WordEntry {
            name: "lifecycle-resource.read",
            domain: "lifecycle-resource",
            func: words::lifecycle_resource_read,
            signature: ":resource-id UUID | :resource-code STRING",
            description: "Read a lifecycle resource",
            examples: &[r#"(lifecycle-resource.read :resource-code "DOC-CHECK")"#],
        },
        WordEntry {
            name: "lifecycle-resource.update",
            domain: "lifecycle-resource",
            func: words::lifecycle_resource_update,
            signature: ":resource-id UUID :name STRING? :status STRING?",
            description: "Update a lifecycle resource",
            examples: &[r#"(lifecycle-resource.update :resource-id "..." :status "ACTIVE")"#],
        },
        WordEntry {
            name: "lifecycle-resource.delete",
            domain: "lifecycle-resource",
            func: words::lifecycle_resource_delete,
            signature: ":resource-id UUID",
            description: "Delete a lifecycle resource",
            examples: &[r#"(lifecycle-resource.delete :resource-id "...")"#],
        },
        WordEntry {
            name: "lifecycle-resource.link-service",
            domain: "lifecycle-resource",
            func: words::lifecycle_resource_link_service,
            signature: ":resource-id UUID :service-id UUID",
            description: "Link a resource to a service",
            examples: &[r#"(lifecycle-resource.link-service :resource-id "..." :service-id "...")"#],
        },
        // ============ ENTITY TYPE CREATION Domain ============
        WordEntry {
            name: "entity.create-proper-person",
            domain: "entity",
            func: words::entity_create_proper_person,
            signature: ":first-name STRING :last-name STRING :middle-name STRING? :date-of-birth DATE? :nationality STRING? :tax-id STRING?",
            description: "Create a proper person (natural individual)",
            examples: &[
                r#"(entity.create-proper-person :first-name "John" :last-name "Smith" :nationality "GB")"#,
            ],
        },
        WordEntry {
            name: "entity.create-limited-company",
            domain: "entity",
            func: words::entity_create_limited_company,
            signature: ":name STRING :jurisdiction STRING? :company-number STRING? :incorporation-date DATE? :registered-office STRING? :share-capital DECIMAL? :currency STRING?",
            description: "Create a limited company entity",
            examples: &[
                r#"(entity.create-limited-company :name "Aviva Investors Ltd" :jurisdiction "GB" :company-number "12345678")"#,
            ],
        },
        WordEntry {
            name: "entity.create-partnership",
            domain: "entity",
            func: words::entity_create_partnership,
            signature: ":name STRING :jurisdiction STRING? :partnership-type STRING? :formation-date DATE? :agreement-date DATE?",
            description: "Create a partnership entity (LP, LLP, GP)",
            examples: &[
                r#"(entity.create-partnership :name "Alpine Capital Partners LLP" :jurisdiction "GB" :partnership-type "LLP")"#,
            ],
        },
        WordEntry {
            name: "entity.create-trust",
            domain: "entity",
            func: words::entity_create_trust,
            signature: ":name STRING :jurisdiction STRING? :trust-type STRING? :governing-law STRING? :formation-date DATE? :is-revocable BOOL?",
            description: "Create a trust entity",
            examples: &[
                r#"(entity.create-trust :name "Pinnacle Discretionary Trust" :jurisdiction "KY" :trust-type "Discretionary")"#,
            ],
        },
        WordEntry {
            name: "entity.read",
            domain: "entity",
            func: words::entity_read,
            signature: ":entity-id UUID",
            description: "Read an entity by ID (returns base + type extension)",
            examples: &[r#"(entity.read :entity-id "550e8400-...")"#],
        },
        WordEntry {
            name: "entity.update",
            domain: "entity",
            func: words::entity_update,
            signature: ":entity-id UUID :name STRING? :jurisdiction STRING?",
            description: "Update an entity's base fields",
            examples: &[r#"(entity.update :entity-id "..." :name "New Name")"#],
        },
        WordEntry {
            name: "entity.delete",
            domain: "entity",
            func: words::entity_delete,
            signature: ":entity-id UUID",
            description: "Delete an entity (cascades to type extension)",
            examples: &[r#"(entity.delete :entity-id "...")"#],
        },
        WordEntry {
            name: "entity.list",
            domain: "entity",
            func: words::entity_list,
            signature: ":entity-type STRING? :jurisdiction STRING?",
            description: "List entities with optional filters",
            examples: &[r#"(entity.list :entity-type "LIMITED_COMPANY" :jurisdiction "GB")"#],
        },
        // ============ CBU ENTITY ATTACHMENT Domain (Hub-Spoke) ============
        WordEntry {
            name: "cbu.detach-entity",
            domain: "cbu",
            func: words::cbu_detach_entity,
            signature: ":cbu-id UUID :entity-id UUID :role STRING?",
            description: "Detach an entity from a CBU (optionally for specific role)",
            examples: &[
                r#"(cbu.detach-entity :cbu-id @cbu :entity-id @company)"#,
                r#"(cbu.detach-entity :cbu-id @cbu :entity-id @person :role "BeneficialOwner")"#,
            ],
        },
        WordEntry {
            name: "cbu.list-entities",
            domain: "cbu",
            func: words::cbu_list_entities,
            signature: ":cbu-id UUID :role STRING?",
            description: "List all entities attached to a CBU (optionally filtered by role)",
            examples: &[
                r#"(cbu.list-entities :cbu-id @cbu)"#,
                r#"(cbu.list-entities :cbu-id @cbu :role "BeneficialOwner")"#,
            ],
        },
        WordEntry {
            name: "cbu.update-entity-role",
            domain: "cbu",
            func: words::cbu_update_entity_role,
            signature: ":cbu-id UUID :entity-id UUID :old-role STRING :new-role STRING",
            description: "Change an entity's role within a CBU",
            examples: &[
                r#"(cbu.update-entity-role :cbu-id @cbu :entity-id @person :old-role "Director" :new-role "BeneficialOwner")"#,
            ],
        },
        // ============ IDEMPOTENT ENSURE VERBS (UPSERT) ============
        WordEntry {
            name: "cbu.ensure",
            domain: "cbu",
            func: words::cbu_ensure,
            signature: ":cbu-name STRING :jurisdiction STRING? :client-type STRING? :nature-purpose STRING?",
            description: "Idempotent CBU create-or-update using natural key (name, jurisdiction)",
            examples: &[
                r#"(cbu.ensure :cbu-name "Meridian Global Fund" :jurisdiction "LU" :client-type "SICAV")"#,
            ],
        },
        WordEntry {
            name: "entity.ensure-limited-company",
            domain: "entity",
            func: words::entity_ensure_limited_company,
            signature: ":name STRING :jurisdiction STRING? :company-number STRING? :incorporation-date DATE?",
            description: "Idempotent limited company create-or-update using natural key (company_number)",
            examples: &[
                r#"(entity.ensure-limited-company :name "Meridian GP S.à r.l." :jurisdiction "LU" :company-number "LU-B234568")"#,
            ],
        },
        WordEntry {
            name: "entity.ensure-proper-person",
            domain: "entity",
            func: words::entity_ensure_proper_person,
            signature: ":first-name STRING :last-name STRING :nationality STRING? :tax-id STRING?",
            description: "Idempotent proper person create-or-update using natural key (tax_id)",
            examples: &[
                r#"(entity.ensure-proper-person :first-name "Chen" :last-name "Wei" :nationality "SG" :tax-id "SG-123456789")"#,
            ],
        },
        WordEntry {
            name: "entity.ensure-ownership",
            domain: "entity",
            func: words::entity_ensure_ownership,
            signature: ":from-entity-id UUID :to-entity-id UUID :ownership-percent DECIMAL :ownership-type STRING? :control-type STRING?",
            description: "Idempotent ownership relationship create-or-update",
            examples: &[
                r#"(entity.ensure-ownership :from-entity-id @gp :to-entity-id @fund :ownership-percent 0.1 :control-type "GENERAL_PARTNER_CONTROL")"#,
            ],
        },
        WordEntry {
            name: "entity.update-ownership",
            domain: "entity",
            func: words::entity_update_ownership,
            signature: ":from-entity-id UUID :to-entity-id UUID :ownership-percent DECIMAL? :effective-date DATE?",
            description: "Update existing ownership relationship",
            examples: &[
                r#"(entity.update-ownership :from-entity-id @holding :to-entity-id @target :ownership-percent 45.0)"#,
            ],
        },
        WordEntry {
            name: "entity.remove-ownership",
            domain: "entity",
            func: words::entity_remove_ownership,
            signature: ":from-entity-id UUID :to-entity-id UUID :effective-date DATE?",
            description: "Remove ownership relationship",
            examples: &[
                r#"(entity.remove-ownership :from-entity-id @holding :to-entity-id @target :effective-date "2024-12-01")"#,
            ],
        },
        WordEntry {
            name: "entity.get-ownership-chain",
            domain: "entity",
            func: words::entity_get_ownership_chain,
            signature: ":target-entity-id UUID :max-depth INTEGER? :threshold DECIMAL?",
            description: "Get full ownership chain to a target entity",
            examples: &[
                r#"(entity.get-ownership-chain :target-entity-id @fund :max-depth 7 :threshold 10.0)"#,
            ],
        },
        // ============ INVESTIGATION DOMAIN ============
        WordEntry {
            name: "investigation.create",
            domain: "investigation",
            func: words::investigation_create,
            signature: ":cbu-id UUID? :investigation-type STRING :risk-rating STRING? :ubo-threshold DECIMAL? :deadline DATE?",
            description: "Create a KYC investigation for a CBU",
            examples: &[
                r#"(investigation.create :cbu-id @cbu :investigation-type "ENHANCED_DUE_DILIGENCE" :risk-rating "HIGH" :ubo-threshold 10.0)"#,
            ],
        },
        WordEntry {
            name: "investigation.update-status",
            domain: "investigation",
            func: words::investigation_update_status,
            signature: ":investigation-id UUID :status STRING",
            description: "Update investigation status",
            examples: &[
                r#"(investigation.update-status :investigation-id @inv :status "COLLECTING_DOCUMENTS")"#,
            ],
        },
        WordEntry {
            name: "investigation.assign",
            domain: "investigation",
            func: words::investigation_assign,
            signature: ":investigation-id UUID :assignee STRING :role STRING?",
            description: "Assign analyst to investigation",
            examples: &[
                r#"(investigation.assign :investigation-id @inv :assignee "analyst@firm.com" :role "PRIMARY_ANALYST")"#,
            ],
        },
        WordEntry {
            name: "investigation.complete",
            domain: "investigation",
            func: words::investigation_complete,
            signature: ":investigation-id UUID :outcome STRING :notes STRING?",
            description: "Complete investigation with outcome",
            examples: &[
                r#"(investigation.complete :investigation-id @inv :outcome "APPROVED" :notes "All UBOs identified")"#,
            ],
        },
        // ============ DOCUMENT COLLECTION DOMAIN ============
        WordEntry {
            name: "document.request",
            domain: "document",
            func: words::document_request,
            signature: ":investigation-id UUID :entity-id UUID? :cbu-id UUID? :document-type STRING :source STRING? :priority STRING?",
            description: "Request a document for an investigation",
            examples: &[
                r#"(document.request :investigation-id @inv :entity-id @company :document-type "CERTIFICATE_OF_INCORPORATION" :source "REGISTRY")"#,
            ],
        },
        WordEntry {
            name: "document.receive",
            domain: "document",
            func: words::document_receive,
            signature: ":request-id UUID :document-id UUID :received-from STRING? :received-date DATE?",
            description: "Record document received",
            examples: &[
                r#"(document.receive :request-id @req :document-id @doc :received-from "Luxembourg Company Registry")"#,
            ],
        },
        // ============ TRUST DOMAIN ============
        WordEntry {
            name: "trust.add-party",
            domain: "trust",
            func: words::trust_add_party,
            signature: ":trust-entity-id UUID :party-entity-id UUID :party-role STRING :interest-percent DECIMAL? :is-discretionary BOOL?",
            description: "Add party to a trust (settlor, trustee, beneficiary, protector)",
            examples: &[
                r#"(trust.add-party :trust-entity-id @trust :party-entity-id @person :party-role "BENEFICIARY" :interest-percent 50.0)"#,
            ],
        },
        // ============ PARTNERSHIP DOMAIN ============
        WordEntry {
            name: "partnership.add-partner",
            domain: "partnership",
            func: words::partnership_add_partner,
            signature: ":partnership-entity-id UUID :partner-entity-id UUID :partner-type STRING :interest-percent DECIMAL? :capital-contribution DECIMAL?",
            description: "Add partner to a partnership",
            examples: &[
                r#"(partnership.add-partner :partnership-entity-id @partnership :partner-entity-id @company :partner-type "LIMITED" :interest-percent 30.0)"#,
            ],
        },
        // ============ UBO DOMAIN (new words) ============
        WordEntry {
            name: "ubo.calculate",
            domain: "ubo",
            func: words::ubo_calculate,
            signature: ":cbu-id UUID :threshold DECIMAL? :max-depth INTEGER? :algorithm STRING?",
            description: "Calculate UBOs for a CBU by traversing ownership graph",
            examples: &[
                r#"(ubo.calculate :cbu-id @cbu :threshold 10.0 :max-depth 7 :algorithm "RECURSIVE_MULTIPLY")"#,
            ],
        },
        WordEntry {
            name: "ubo.flag",
            domain: "ubo",
            func: words::ubo_flag,
            signature: ":cbu-id UUID :entity-id UUID :ownership-percent DECIMAL? :flag-reason STRING :flagged-by STRING?",
            description: "Manually flag a UBO (override calculation)",
            examples: &[
                r#"(ubo.flag :cbu-id @cbu :entity-id @person :ownership-percent 8.0 :flag-reason "MATERIAL_INFLUENCE")"#,
            ],
        },
        WordEntry {
            name: "ubo.verify",
            domain: "ubo",
            func: words::ubo_verify,
            signature: ":ubo-id UUID :verification-method STRING :verified-by STRING? :notes STRING?",
            description: "Verify a calculated UBO",
            examples: &[
                r#"(ubo.verify :ubo-id @ubo :verification-method "DOCUMENT_REVIEW" :verified-by "analyst@firm.com")"#,
            ],
        },
        WordEntry {
            name: "ubo.clear",
            domain: "ubo",
            func: words::ubo_clear,
            signature: ":ubo-id UUID :reason STRING :effective-date DATE?",
            description: "Clear a UBO flag (entity sold stake, etc.)",
            examples: &[
                r#"(ubo.clear :ubo-id @ubo :reason "OWNERSHIP_BELOW_THRESHOLD" :effective-date "2024-12-01")"#,
            ],
        },
        // ============ SCREENING DOMAIN ============
        WordEntry {
            name: "screening.pep",
            domain: "screening",
            func: words::screening_pep,
            signature: ":entity-id UUID :databases LIST? :include-rca BOOL?",
            description: "PEP screening for an entity",
            examples: &[
                r#"(screening.pep :entity-id @person :databases ["WORLD_CHECK" "REFINITIV"] :include-rca true)"#,
            ],
        },
        WordEntry {
            name: "screening.sanctions",
            domain: "screening",
            func: words::screening_sanctions,
            signature: ":entity-id UUID :lists LIST?",
            description: "Sanctions screening for an entity",
            examples: &[
                r#"(screening.sanctions :entity-id @company :lists ["OFAC_SDN" "EU_SANCTIONS" "UK_HMT"])"#,
            ],
        },
        WordEntry {
            name: "screening.adverse-media",
            domain: "screening",
            func: words::screening_adverse_media,
            signature: ":entity-id UUID :depth STRING? :languages LIST?",
            description: "Adverse media screening for an entity",
            examples: &[
                r#"(screening.adverse-media :entity-id @person :depth "DEEP" :languages ["EN" "DE" "FR"])"#,
            ],
        },
        WordEntry {
            name: "screening.record-result",
            domain: "screening",
            func: words::screening_record_result,
            signature: ":screening-id UUID :result STRING :match-details MAP? :reviewed-by STRING?",
            description: "Record screening result",
            examples: &[
                r#"(screening.record-result :screening-id @screening :result "MATCH" :match-details {:list "OFAC_SDN" :match-score 95})"#,
            ],
        },
        WordEntry {
            name: "screening.resolve",
            domain: "screening",
            func: words::screening_resolve,
            signature: ":screening-id UUID :resolution STRING :rationale STRING? :resolved-by STRING?",
            description: "Resolve screening match (false positive, true hit, etc.)",
            examples: &[
                r#"(screening.resolve :screening-id @screening :resolution "FALSE_POSITIVE" :rationale "Different person - DOB mismatch")"#,
            ],
        },
        // ============ RISK DOMAIN ============
        WordEntry {
            name: "risk.assess-entity",
            domain: "risk",
            func: words::risk_assess_entity,
            signature: ":entity-id UUID :factors LIST?",
            description: "Assess entity risk",
            examples: &[
                r#"(risk.assess-entity :entity-id @person :factors ["PEP_STATUS" "JURISDICTION" "SOURCE_OF_WEALTH"])"#,
            ],
        },
        WordEntry {
            name: "risk.assess-cbu",
            domain: "risk",
            func: words::risk_assess_cbu,
            signature: ":cbu-id UUID :methodology STRING?",
            description: "Assess CBU overall risk",
            examples: &[
                r#"(risk.assess-cbu :cbu-id @cbu :methodology "FACTOR_WEIGHTED")"#,
            ],
        },
        WordEntry {
            name: "risk.set-rating",
            domain: "risk",
            func: words::risk_set_rating,
            signature: ":cbu-id UUID? :entity-id UUID? :rating STRING :factors LIST? :rationale STRING? :assessed-by STRING?",
            description: "Set risk rating (manual or calculated)",
            examples: &[
                r#"(risk.set-rating :cbu-id @cbu :rating "HIGH" :factors [{:factor "PEP_EXPOSURE" :rating "HIGH"}] :rationale "PEP UBO")"#,
            ],
        },
        WordEntry {
            name: "risk.add-flag",
            domain: "risk",
            func: words::risk_add_flag,
            signature: ":cbu-id UUID? :entity-id UUID? :flag-type STRING :description STRING? :flagged-by STRING?",
            description: "Add risk flag (red flag, amber flag, note)",
            examples: &[
                r#"(risk.add-flag :cbu-id @cbu :flag-type "RED_FLAG" :description "Trust beneficiaries not disclosed")"#,
            ],
        },
        // ============ DECISION DOMAIN ============
        WordEntry {
            name: "decision.record",
            domain: "decision",
            func: words::decision_record,
            signature: ":cbu-id UUID :investigation-id UUID? :decision STRING :decision-authority STRING? :rationale STRING? :decided-by STRING?",
            description: "Record onboarding decision",
            examples: &[
                r#"(decision.record :cbu-id @cbu :investigation-id @inv :decision "CONDITIONAL_ACCEPTANCE" :decision-authority "SENIOR_MANAGEMENT")"#,
            ],
        },
        WordEntry {
            name: "decision.add-condition",
            domain: "decision",
            func: words::decision_add_condition,
            signature: ":decision-id UUID :condition-type STRING :description STRING? :frequency STRING? :due-date DATE? :threshold DECIMAL? :currency STRING?",
            description: "Add condition to conditional acceptance",
            examples: &[
                r#"(decision.add-condition :decision-id @decision :condition-type "ENHANCED_MONITORING" :frequency "QUARTERLY")"#,
            ],
        },
        WordEntry {
            name: "decision.satisfy-condition",
            domain: "decision",
            func: words::decision_satisfy_condition,
            signature: ":condition-id UUID :satisfied-by STRING? :evidence STRING?",
            description: "Mark condition as satisfied",
            examples: &[
                r#"(decision.satisfy-condition :condition-id @condition :satisfied-by "analyst@firm.com" :evidence "Trust beneficiaries disclosed")"#,
            ],
        },
        WordEntry {
            name: "decision.review",
            domain: "decision",
            func: words::decision_review,
            signature: ":decision-id UUID :review-date DATE? :reviewed-by STRING?",
            description: "Review/update a decision",
            examples: &[
                r#"(decision.review :decision-id @decision :review-date "2025-01-15")"#,
            ],
        },
        // ============ MONITORING DOMAIN ============
        WordEntry {
            name: "monitoring.setup",
            domain: "monitoring",
            func: words::monitoring_setup,
            signature: ":cbu-id UUID :monitoring-level STRING :components LIST?",
            description: "Setup ongoing monitoring for a CBU",
            examples: &[
                r#"(monitoring.setup :cbu-id @cbu :monitoring-level "ENHANCED" :components [{:type "TRANSACTION_MONITORING" :frequency "REAL_TIME"}])"#,
            ],
        },
        WordEntry {
            name: "monitoring.record-event",
            domain: "monitoring",
            func: words::monitoring_record_event,
            signature: ":cbu-id UUID :event-type STRING :description STRING? :severity STRING? :requires-review BOOL?",
            description: "Record a monitoring event",
            examples: &[
                r#"(monitoring.record-event :cbu-id @cbu :event-type "TRANSACTION_ALERT" :severity "HIGH" :requires-review true)"#,
            ],
        },
        WordEntry {
            name: "monitoring.schedule-review",
            domain: "monitoring",
            func: words::monitoring_schedule_review,
            signature: ":cbu-id UUID :review-type STRING :due-date DATE :assigned-to STRING?",
            description: "Schedule a periodic review",
            examples: &[
                r#"(monitoring.schedule-review :cbu-id @cbu :review-type "ANNUAL_KYC_REFRESH" :due-date "2025-01-15" :assigned-to "analyst@firm.com")"#,
            ],
        },
        WordEntry {
            name: "monitoring.complete-review",
            domain: "monitoring",
            func: words::monitoring_complete_review,
            signature: ":review-id UUID :completed-by STRING :notes STRING?",
            description: "Complete a scheduled review",
            examples: &[
                r#"(monitoring.complete-review :review-id @review :completed-by "analyst@firm.com" :notes "All checks passed")"#,
            ],
        },
    ])
}
