//! Decision domain verb definitions.
//!
//! Covers recording decisions, approvals, rejections,
//! escalations, and conditional approvals.

use crate::forth_engine::schema::types::*;

pub static DECISION_RECORD: VerbDef = VerbDef {
    name: "decision.record",
    domain: "decision",
    args: &[
        ArgSpec {
            name: ":investigation-id",
            sem_type: SemType::Uuid,
            required: RequiredRule::Never,
            default: Some(DefaultValue::FromContext(ContextKey::InvestigationId)),
            validation: &[],
            description: "Investigation this decision relates to",
        },
        ArgSpec {
            name: ":decision-type",
            sem_type: SemType::Enum(&["APPROVE", "REJECT", "ESCALATE", "DEFER", "CONDITIONAL_APPROVE"]),
            required: RequiredRule::Always,
            default: None,
            validation: &[],
            description: "Type of decision",
        },
        ArgSpec {
            name: ":rationale",
            sem_type: SemType::String,
            required: RequiredRule::Always,
            default: None,
            validation: &[ValidationRule::NotEmpty, ValidationRule::Length { min: Some(10), max: Some(4000) }],
            description: "Detailed rationale for the decision",
        },
        ArgSpec {
            name: ":decided-by",
            sem_type: SemType::String,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Person or committee making the decision",
        },
        ArgSpec {
            name: ":decision-date",
            sem_type: SemType::Date,
            required: RequiredRule::Never,
            default: None,
            validation: &[ValidationRule::DateRange { min: None, max: Some(DateBound::Today) }],
            description: "Date of decision (defaults to today)",
        },
        ArgSpec {
            name: ":as",
            sem_type: SemType::Symbol,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Symbol to capture decision ID",
        },
    ],
    constraints: &[],
    produces: Some(ProducesSpec {
        capture_as: ContextKey::DecisionId,
        description: "The decision UUID",
    }),
    crud_asset: "DECISION",
    description: "Record a decision for an investigation",
    examples: &[
        r#"(decision.record :decision-type "APPROVE" :rationale "All KYC requirements satisfied" :as @decision)"#,
        r#"(decision.record :decision-type "REJECT" :rationale "Unable to verify source of funds" :decided-by "Compliance Committee")"#,
    ],
};

pub static DECISION_APPROVE: VerbDef = VerbDef {
    name: "decision.approve",
    domain: "decision",
    args: &[
        ArgSpec {
            name: ":investigation-id",
            sem_type: SemType::Uuid,
            required: RequiredRule::Never,
            default: Some(DefaultValue::FromContext(ContextKey::InvestigationId)),
            validation: &[],
            description: "Investigation to approve",
        },
        ArgSpec {
            name: ":cbu-id",
            sem_type: SemType::Uuid,
            required: RequiredRule::Never,
            default: Some(DefaultValue::FromContext(ContextKey::CbuId)),
            validation: &[],
            description: "CBU being approved",
        },
        ArgSpec {
            name: ":rationale",
            sem_type: SemType::String,
            required: RequiredRule::Always,
            default: None,
            validation: &[ValidationRule::NotEmpty],
            description: "Reason for approval",
        },
        ArgSpec {
            name: ":approved-by",
            sem_type: SemType::String,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Approver name or role",
        },
        ArgSpec {
            name: ":approval-level",
            sem_type: SemType::Enum(&["ANALYST", "SENIOR_ANALYST", "MANAGER", "DIRECTOR", "COMMITTEE"]),
            required: RequiredRule::Never,
            default: Some(DefaultValue::Str("ANALYST")),
            validation: &[],
            description: "Level of approval authority",
        },
        ArgSpec {
            name: ":effective-date",
            sem_type: SemType::Date,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "When approval becomes effective",
        },
        ArgSpec {
            name: ":review-date",
            sem_type: SemType::Date,
            required: RequiredRule::Never,
            default: None,
            validation: &[ValidationRule::DateRange { min: Some(DateBound::Today), max: None }],
            description: "Next scheduled review date",
        },
        ArgSpec {
            name: ":as",
            sem_type: SemType::Symbol,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Symbol to capture decision ID",
        },
    ],
    constraints: &[],
    produces: Some(ProducesSpec {
        capture_as: ContextKey::DecisionId,
        description: "The approval decision UUID",
    }),
    crud_asset: "DECISION",
    description: "Approve an investigation/CBU for onboarding",
    examples: &[
        r#"(decision.approve :rationale "Full KYC complete, low risk" :approved-by "John Smith" :as @approval)"#,
        r#"(decision.approve :rationale "EDD complete" :approval-level "DIRECTOR" :review-date "2025-11-26")"#,
    ],
};

pub static DECISION_REJECT: VerbDef = VerbDef {
    name: "decision.reject",
    domain: "decision",
    args: &[
        ArgSpec {
            name: ":investigation-id",
            sem_type: SemType::Uuid,
            required: RequiredRule::Never,
            default: Some(DefaultValue::FromContext(ContextKey::InvestigationId)),
            validation: &[],
            description: "Investigation to reject",
        },
        ArgSpec {
            name: ":cbu-id",
            sem_type: SemType::Uuid,
            required: RequiredRule::Never,
            default: Some(DefaultValue::FromContext(ContextKey::CbuId)),
            validation: &[],
            description: "CBU being rejected",
        },
        ArgSpec {
            name: ":reason-code",
            sem_type: SemType::Enum(&[
                "SANCTIONS_HIT", "PEP_UNRESOLVED", "SOURCE_OF_FUNDS",
                "ADVERSE_MEDIA", "DOCUMENTATION_INCOMPLETE", "HIGH_RISK_JURISDICTION",
                "BENEFICIAL_OWNER_UNVERIFIED", "REGULATORY_PROHIBITION", "OTHER"
            ]),
            required: RequiredRule::Always,
            default: None,
            validation: &[],
            description: "Primary reason for rejection",
        },
        ArgSpec {
            name: ":rationale",
            sem_type: SemType::String,
            required: RequiredRule::Always,
            default: None,
            validation: &[ValidationRule::NotEmpty, ValidationRule::Length { min: Some(20), max: Some(4000) }],
            description: "Detailed explanation for rejection",
        },
        ArgSpec {
            name: ":rejected-by",
            sem_type: SemType::String,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Person rejecting",
        },
        ArgSpec {
            name: ":is-permanent",
            sem_type: SemType::Boolean,
            required: RequiredRule::Never,
            default: Some(DefaultValue::Bool(false)),
            validation: &[],
            description: "Whether rejection is permanent (no reapply)",
        },
        ArgSpec {
            name: ":reapply-after",
            sem_type: SemType::Date,
            required: RequiredRule::Never,
            default: None,
            validation: &[ValidationRule::DateRange { min: Some(DateBound::Today), max: None }],
            description: "Earliest date client can reapply",
        },
        ArgSpec {
            name: ":as",
            sem_type: SemType::Symbol,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Symbol to capture decision ID",
        },
    ],
    constraints: &[
        CrossConstraint::Excludes { if_present: ":is-permanent", then_forbid: ":reapply-after" },
    ],
    produces: Some(ProducesSpec {
        capture_as: ContextKey::DecisionId,
        description: "The rejection decision UUID",
    }),
    crud_asset: "DECISION",
    description: "Reject an investigation/CBU",
    examples: &[
        r#"(decision.reject :reason-code "SANCTIONS_HIT" :rationale "Confirmed OFAC SDN match" :is-permanent true)"#,
        r#"(decision.reject :reason-code "DOCUMENTATION_INCOMPLETE" :rationale "Missing certified articles" :reapply-after "2025-03-01")"#,
    ],
};

pub static DECISION_ESCALATE: VerbDef = VerbDef {
    name: "decision.escalate",
    domain: "decision",
    args: &[
        ArgSpec {
            name: ":investigation-id",
            sem_type: SemType::Uuid,
            required: RequiredRule::Never,
            default: Some(DefaultValue::FromContext(ContextKey::InvestigationId)),
            validation: &[],
            description: "Investigation to escalate",
        },
        ArgSpec {
            name: ":escalate-to",
            sem_type: SemType::Enum(&["SENIOR_ANALYST", "MANAGER", "DIRECTOR", "COMMITTEE", "MLRO", "LEGAL"]),
            required: RequiredRule::Always,
            default: None,
            validation: &[],
            description: "Level to escalate to",
        },
        ArgSpec {
            name: ":reason",
            sem_type: SemType::Enum(&[
                "HIGH_RISK", "PEP_INVOLVEMENT", "SANCTIONS_HIT", "COMPLEX_STRUCTURE",
                "UNUSUAL_ACTIVITY", "POLICY_EXCEPTION", "SENIOR_APPROVAL_REQUIRED", "OTHER"
            ]),
            required: RequiredRule::Always,
            default: None,
            validation: &[],
            description: "Reason for escalation",
        },
        ArgSpec {
            name: ":summary",
            sem_type: SemType::String,
            required: RequiredRule::Always,
            default: None,
            validation: &[ValidationRule::NotEmpty, ValidationRule::Length { min: Some(20), max: Some(2000) }],
            description: "Summary of the case for reviewer",
        },
        ArgSpec {
            name: ":escalated-by",
            sem_type: SemType::String,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Person escalating",
        },
        ArgSpec {
            name: ":priority",
            sem_type: SemType::Enum(&["LOW", "NORMAL", "HIGH", "URGENT"]),
            required: RequiredRule::Never,
            default: Some(DefaultValue::Str("NORMAL")),
            validation: &[],
            description: "Priority of escalation",
        },
        ArgSpec {
            name: ":due-date",
            sem_type: SemType::Date,
            required: RequiredRule::Never,
            default: None,
            validation: &[ValidationRule::DateRange { min: Some(DateBound::Today), max: None }],
            description: "When escalation should be resolved",
        },
        ArgSpec {
            name: ":as",
            sem_type: SemType::Symbol,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Symbol to capture escalation ID",
        },
    ],
    constraints: &[],
    produces: Some(ProducesSpec {
        capture_as: ContextKey::DecisionId,
        description: "The escalation decision UUID",
    }),
    crud_asset: "DECISION",
    description: "Escalate investigation for senior review",
    examples: &[
        r#"(decision.escalate :escalate-to "COMMITTEE" :reason "PEP_INVOLVEMENT" :summary "Director is a current PEP" :priority "HIGH")"#,
    ],
};

pub static DECISION_ADD_CONDITION: VerbDef = VerbDef {
    name: "decision.add-condition",
    domain: "decision",
    args: &[
        ArgSpec {
            name: ":decision-id",
            sem_type: SemType::Uuid,
            required: RequiredRule::Never,
            default: Some(DefaultValue::FromContext(ContextKey::DecisionId)),
            validation: &[],
            description: "Decision to add condition to",
        },
        ArgSpec {
            name: ":condition-type",
            sem_type: SemType::Enum(&[
                "DOCUMENT_REQUIRED", "ENHANCED_MONITORING", "TRANSACTION_LIMIT",
                "PERIODIC_REVIEW", "SENIOR_SIGN_OFF", "REGULATORY_APPROVAL", "OTHER"
            ]),
            required: RequiredRule::Always,
            default: None,
            validation: &[],
            description: "Type of condition",
        },
        ArgSpec {
            name: ":description",
            sem_type: SemType::String,
            required: RequiredRule::Always,
            default: None,
            validation: &[ValidationRule::NotEmpty],
            description: "Description of the condition",
        },
        ArgSpec {
            name: ":due-date",
            sem_type: SemType::Date,
            required: RequiredRule::Never,
            default: None,
            validation: &[ValidationRule::DateRange { min: Some(DateBound::Today), max: None }],
            description: "When condition must be satisfied",
        },
        ArgSpec {
            name: ":blocking",
            sem_type: SemType::Boolean,
            required: RequiredRule::Never,
            default: Some(DefaultValue::Bool(false)),
            validation: &[],
            description: "Whether condition blocks account activity",
        },
    ],
    constraints: &[],
    produces: None,
    crud_asset: "DECISION_CONDITION",
    description: "Add a condition to a conditional approval",
    examples: &[
        r#"(decision.add-condition :condition-type "DOCUMENT_REQUIRED" :description "Provide audited accounts within 30 days" :due-date "2025-12-26" :blocking true)"#,
        r#"(decision.add-condition :condition-type "ENHANCED_MONITORING" :description "Monthly transaction review for 6 months")"#,
    ],
};

pub static DECISION_SATISFY_CONDITION: VerbDef = VerbDef {
    name: "decision.satisfy-condition",
    domain: "decision",
    args: &[
        ArgSpec {
            name: ":condition-id",
            sem_type: SemType::Uuid,
            required: RequiredRule::Always,
            default: None,
            validation: &[],
            description: "Condition to satisfy",
        },
        ArgSpec {
            name: ":evidence",
            sem_type: SemType::String,
            required: RequiredRule::Always,
            default: None,
            validation: &[ValidationRule::NotEmpty],
            description: "Evidence that condition is satisfied",
        },
        ArgSpec {
            name: ":satisfied-by",
            sem_type: SemType::String,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Person confirming satisfaction",
        },
        ArgSpec {
            name: ":document-refs",
            sem_type: SemType::ListOf(&SemType::String),
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "References to supporting documents",
        },
    ],
    constraints: &[],
    produces: None,
    crud_asset: "DECISION_CONDITION",
    description: "Mark a condition as satisfied",
    examples: &[
        r#"(decision.satisfy-condition :condition-id "COND-001" :evidence "Audited accounts received and verified" :document-refs ["DOC-123"])"#,
    ],
};

pub static DECISION_DEFER: VerbDef = VerbDef {
    name: "decision.defer",
    domain: "decision",
    args: &[
        ArgSpec {
            name: ":investigation-id",
            sem_type: SemType::Uuid,
            required: RequiredRule::Never,
            default: Some(DefaultValue::FromContext(ContextKey::InvestigationId)),
            validation: &[],
            description: "Investigation to defer",
        },
        ArgSpec {
            name: ":defer-until",
            sem_type: SemType::Date,
            required: RequiredRule::Always,
            default: None,
            validation: &[ValidationRule::DateRange { min: Some(DateBound::Today), max: None }],
            description: "Date to revisit the decision",
        },
        ArgSpec {
            name: ":reason",
            sem_type: SemType::String,
            required: RequiredRule::Always,
            default: None,
            validation: &[ValidationRule::NotEmpty],
            description: "Reason for deferral",
        },
        ArgSpec {
            name: ":pending-items",
            sem_type: SemType::ListOf(&SemType::String),
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Items that need resolution before decision",
        },
        ArgSpec {
            name: ":as",
            sem_type: SemType::Symbol,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Symbol to capture deferral ID",
        },
    ],
    constraints: &[],
    produces: Some(ProducesSpec {
        capture_as: ContextKey::DecisionId,
        description: "The deferral decision UUID",
    }),
    crud_asset: "DECISION",
    description: "Defer decision pending additional information",
    examples: &[
        r#"(decision.defer :defer-until "2025-12-15" :reason "Awaiting third-party verification" :pending-items ["Source of funds verification"])"#,
    ],
};
