//! Entity domain verb definitions.

use crate::forth_engine::schema::types::*;

pub static ENTITY_CREATE_LIMITED_COMPANY: VerbDef = VerbDef {
    name: "entity.create-limited-company",
    domain: "entity",
    args: &[
        ArgSpec {
            name: ":name",
            sem_type: SemType::String,
            required: RequiredRule::Always,
            default: None,
            validation: &[ValidationRule::NotEmpty, ValidationRule::Length { min: Some(1), max: Some(255) }],
            description: "Company name",
        },
        ArgSpec {
            name: ":jurisdiction",
            sem_type: SemType::Ref(RefType::Jurisdiction),
            required: RequiredRule::Always,
            default: None,
            validation: &[ValidationRule::LookupMustExist],
            description: "Country of incorporation (ISO code)",
        },
        ArgSpec {
            name: ":company-number",
            sem_type: SemType::String,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Official company registration number",
        },
        ArgSpec {
            name: ":incorporation-date",
            sem_type: SemType::Date,
            required: RequiredRule::Never,
            default: None,
            validation: &[ValidationRule::DateRange { min: None, max: Some(DateBound::Today) }],
            description: "Date of incorporation (cannot be in future)",
        },
        ArgSpec {
            name: ":registered-office",
            sem_type: SemType::String,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Registered office address",
        },
        ArgSpec {
            name: ":share-capital",
            sem_type: SemType::Decimal,
            required: RequiredRule::Never,
            default: None,
            validation: &[ValidationRule::Range { min: Some(0.0), max: None }],
            description: "Share capital amount",
        },
        ArgSpec {
            name: ":currency",
            sem_type: SemType::Ref(RefType::Currency),
            required: RequiredRule::IfProvided(":share-capital"),
            default: None,
            validation: &[],
            description: "Currency for share capital",
        },
        ArgSpec {
            name: ":as",
            sem_type: SemType::Symbol,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Symbol name to capture entity ID",
        },
    ],
    constraints: &[],
    produces: Some(ProducesSpec {
        capture_as: ContextKey::EntityId,
        description: "The entity UUID",
    }),
    crud_asset: "LIMITED_COMPANY",
    description: "Create a limited company entity",
    examples: &[
        r#"(entity.create-limited-company :name "Aviva Investors Ltd" :jurisdiction "GB" :as @aviva)"#,
    ],
};

pub static ENTITY_CREATE_PROPER_PERSON: VerbDef = VerbDef {
    name: "entity.create-proper-person",
    domain: "entity",
    args: &[
        ArgSpec {
            name: ":first-name",
            sem_type: SemType::String,
            required: RequiredRule::Always,
            default: None,
            validation: &[ValidationRule::NotEmpty],
            description: "First name",
        },
        ArgSpec {
            name: ":last-name",
            sem_type: SemType::String,
            required: RequiredRule::Always,
            default: None,
            validation: &[ValidationRule::NotEmpty],
            description: "Last name / surname",
        },
        ArgSpec {
            name: ":middle-name",
            sem_type: SemType::String,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Middle name(s)",
        },
        ArgSpec {
            name: ":date-of-birth",
            sem_type: SemType::Date,
            required: RequiredRule::Never,
            default: None,
            validation: &[ValidationRule::DateRange { 
                min: Some(DateBound::Literal("1900-01-01")), 
                max: Some(DateBound::Today) 
            }],
            description: "Date of birth",
        },
        ArgSpec {
            name: ":nationality",
            sem_type: SemType::Ref(RefType::Jurisdiction),
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Nationality (country code)",
        },
        ArgSpec {
            name: ":tax-id",
            sem_type: SemType::String,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Tax identification number",
        },
        ArgSpec {
            name: ":as",
            sem_type: SemType::Symbol,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Symbol name to capture entity ID",
        },
    ],
    constraints: &[],
    produces: Some(ProducesSpec {
        capture_as: ContextKey::EntityId,
        description: "The person entity UUID",
    }),
    crud_asset: "PROPER_PERSON",
    description: "Create a natural person entity",
    examples: &[
        r#"(entity.create-proper-person :first-name "John" :last-name "Smith" :as @john)"#,
    ],
};

pub static ENTITY_CREATE_PARTNERSHIP: VerbDef = VerbDef {
    name: "entity.create-partnership",
    domain: "entity",
    args: &[
        ArgSpec {
            name: ":name",
            sem_type: SemType::String,
            required: RequiredRule::Always,
            default: None,
            validation: &[ValidationRule::NotEmpty],
            description: "Partnership name",
        },
        ArgSpec {
            name: ":jurisdiction",
            sem_type: SemType::Ref(RefType::Jurisdiction),
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Jurisdiction of formation",
        },
        ArgSpec {
            name: ":partnership-type",
            sem_type: SemType::Enum(&["LP", "LLP", "GP", "LLLP"]),
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Type of partnership",
        },
        ArgSpec {
            name: ":formation-date",
            sem_type: SemType::Date,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Date of formation",
        },
        ArgSpec {
            name: ":as",
            sem_type: SemType::Symbol,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Symbol to capture entity ID",
        },
    ],
    constraints: &[],
    produces: Some(ProducesSpec {
        capture_as: ContextKey::EntityId,
        description: "The partnership entity UUID",
    }),
    crud_asset: "PARTNERSHIP",
    description: "Create a partnership entity (LP, LLP, GP)",
    examples: &[
        r#"(entity.create-partnership :name "Alpine Capital Partners LLP" :jurisdiction "GB" :partnership-type "LLP")"#,
    ],
};

pub static ENTITY_CREATE_TRUST: VerbDef = VerbDef {
    name: "entity.create-trust",
    domain: "entity",
    args: &[
        ArgSpec {
            name: ":name",
            sem_type: SemType::String,
            required: RequiredRule::Always,
            default: None,
            validation: &[ValidationRule::NotEmpty],
            description: "Trust name",
        },
        ArgSpec {
            name: ":jurisdiction",
            sem_type: SemType::Ref(RefType::Jurisdiction),
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Governing jurisdiction",
        },
        ArgSpec {
            name: ":trust-type",
            sem_type: SemType::Enum(&["Discretionary", "Fixed", "Bare", "Charitable", "Unit"]),
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Type of trust",
        },
        ArgSpec {
            name: ":governing-law",
            sem_type: SemType::String,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Governing law",
        },
        ArgSpec {
            name: ":formation-date",
            sem_type: SemType::Date,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Date of formation",
        },
        ArgSpec {
            name: ":is-revocable",
            sem_type: SemType::Boolean,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Whether the trust is revocable",
        },
        ArgSpec {
            name: ":as",
            sem_type: SemType::Symbol,
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Symbol to capture entity ID",
        },
    ],
    constraints: &[],
    produces: Some(ProducesSpec {
        capture_as: ContextKey::EntityId,
        description: "The trust entity UUID",
    }),
    crud_asset: "TRUST",
    description: "Create a trust entity",
    examples: &[
        r#"(entity.create-trust :name "Pinnacle Trust" :jurisdiction "KY" :trust-type "Discretionary")"#,
    ],
};

pub static ENTITY_ENSURE_OWNERSHIP: VerbDef = VerbDef {
    name: "entity.ensure-ownership",
    domain: "entity",
    args: &[
        ArgSpec {
            name: ":from-entity-id",
            sem_type: SemType::Symbol,
            required: RequiredRule::Always,
            default: None,
            validation: &[],
            description: "Owner entity",
        },
        ArgSpec {
            name: ":to-entity-id",
            sem_type: SemType::Symbol,
            required: RequiredRule::Always,
            default: None,
            validation: &[],
            description: "Owned entity",
        },
        ArgSpec {
            name: ":ownership-percent",
            sem_type: SemType::Decimal,
            required: RequiredRule::Always,
            default: None,
            validation: &[ValidationRule::Range { min: Some(0.0), max: Some(100.0) }],
            description: "Ownership percentage",
        },
        ArgSpec {
            name: ":ownership-type",
            sem_type: SemType::Enum(&["DIRECT", "INDIRECT", "BENEFICIAL"]),
            required: RequiredRule::Never,
            default: Some(DefaultValue::Str("DIRECT")),
            validation: &[],
            description: "Type of ownership",
        },
        ArgSpec {
            name: ":control-type",
            sem_type: SemType::Enum(&["VOTING", "ECONOMIC", "GENERAL_PARTNER_CONTROL", "NONE"]),
            required: RequiredRule::Never,
            default: None,
            validation: &[],
            description: "Type of control",
        },
    ],
    constraints: &[],
    produces: None,
    crud_asset: "OWNERSHIP",
    description: "Create or update ownership relationship between entities",
    examples: &[
        r#"(entity.ensure-ownership :from-entity-id @gp :to-entity-id @fund :ownership-percent 0.1)"#,
    ],
};
