; Generated by verb_to_dsl from config/verbs/research/sec-edgar.yaml
; DO NOT EDIT — regenerate with `cargo run --bin verb_to_dsl`

(utterance-binding research.sec-edgar :invocation-hints ["SEC" "EDGAR" "US company" "American company" "CIK" "13D" "13G" "beneficial ownership" "public company" "SEC filings"])

(verb research.sec-edgar.fetch-beneficial-owners
  :description "Fetch 13D/13G beneficial ownership filings"
  :behavior "plugin"
  :handler "SecFetchBeneficialOwnersOp"
  :effect-class "read_snapshot"
  :flavour "attribute_mutating"
  :metadata-json "{\"tier\":\"diagnostics\",\"source_of_truth\":\"external\",\"scope\":\"global\",\"writes_operational\":false,\"side_effects\":\"state_write\",\"harm_class\":null,\"action_class\":null,\"noun\":\"beneficial_owner\",\"internal\":false,\"tags\":[\"read\",\"external-source\",\"registry-fetch\",\"ownership\"],\"replaces\":null,\"status\":\"active\",\"replaced_by\":null,\"since_version\":null,\"removal_version\":null,\"dangerous\":false,\"subject_kinds\":[],\"phase_tags\":[\"onboarding\"],\"requires_subject\":true,\"produces_focus\":false}"
  :three-axis-json "{\"state_effect\":\"preserving\",\"external_effects\":[\"observational\"],\"consequence\":{\"baseline\":\"benign\",\"escalation\":[]}}"
  :returns-json "{\"type\":\"record_set\",\"name\":null,\"capture\":null}"
  :args-json "[{\"name\":\"cik\",\"type\":\"string\",\"required\":true,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":\"SEC CIK number\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"include-13d\",\"type\":\"boolean\",\"required\":false,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":true,\"description\":\"Include 13D filings (activist ownership)\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"include-13g\",\"type\":\"boolean\",\"required\":false,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":true,\"description\":\"Include 13G filings (passive ownership)\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"since-date\",\"type\":\"date\",\"required\":false,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":\"Only filings after this date\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"decision-id\",\"type\":\"uuid\",\"required\":false,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":\"Research decision ID for audit trail\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]}]"
)

(utterance-binding research.sec-edgar.fetch-beneficial-owners :phrases ["get 13D filings" "13G beneficial owners" "who owns this US company" "SEC beneficial ownership"] :verb research.sec-edgar.fetch-beneficial-owners)

(verb research.sec-edgar.fetch-company
  :description "Fetch company information from SEC EDGAR"
  :behavior "plugin"
  :handler "SecFetchCompanyOp"
  :effect-class "read_snapshot"
  :flavour "attribute_mutating"
  :metadata-json "{\"tier\":\"diagnostics\",\"source_of_truth\":\"external\",\"scope\":\"global\",\"writes_operational\":false,\"side_effects\":\"state_write\",\"harm_class\":null,\"action_class\":null,\"noun\":\"company_profile\",\"internal\":false,\"tags\":[\"read\",\"external-source\",\"registry-fetch\"],\"replaces\":null,\"status\":\"active\",\"replaced_by\":null,\"since_version\":null,\"removal_version\":null,\"dangerous\":false,\"subject_kinds\":[],\"phase_tags\":[\"onboarding\"],\"requires_subject\":true,\"produces_focus\":false}"
  :three-axis-json "{\"state_effect\":\"preserving\",\"external_effects\":[\"observational\"],\"consequence\":{\"baseline\":\"benign\",\"escalation\":[]}}"
  :returns-json "{\"type\":\"record\",\"name\":null,\"capture\":null}"
  :args-json "[{\"name\":\"cik\",\"type\":\"string\",\"required\":true,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":\"SEC CIK number (10 digits, zero-padded)\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"decision-id\",\"type\":\"uuid\",\"required\":false,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":\"Research decision ID for audit trail\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]}]"
)

(utterance-binding research.sec-edgar.fetch-company :phrases ["get SEC company" "fetch from EDGAR" "company from SEC"] :verb research.sec-edgar.fetch-company)

(verb research.sec-edgar.fetch-filings
  :description "Fetch recent SEC filings for a company"
  :behavior "plugin"
  :handler "SecFetchFilingsOp"
  :effect-class "read_snapshot"
  :flavour "attribute_mutating"
  :metadata-json "{\"tier\":\"diagnostics\",\"source_of_truth\":\"external\",\"scope\":\"global\",\"writes_operational\":false,\"side_effects\":\"state_write\",\"harm_class\":null,\"action_class\":null,\"noun\":\"filing\",\"internal\":false,\"tags\":[\"read\",\"external-source\",\"registry-fetch\"],\"replaces\":null,\"status\":\"active\",\"replaced_by\":null,\"since_version\":null,\"removal_version\":null,\"dangerous\":false,\"subject_kinds\":[],\"phase_tags\":[\"onboarding\"],\"requires_subject\":true,\"produces_focus\":false}"
  :three-axis-json "{\"state_effect\":\"preserving\",\"external_effects\":[\"observational\"],\"consequence\":{\"baseline\":\"benign\",\"escalation\":[]}}"
  :returns-json "{\"type\":\"record_set\",\"name\":null,\"capture\":null}"
  :args-json "[{\"name\":\"cik\",\"type\":\"string\",\"required\":true,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":\"SEC CIK number\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"form-types\",\"type\":\"string_list\",\"required\":false,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":\"Filter by form type (10-K, 10-Q, 8-K, etc.)\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"limit\",\"type\":\"integer\",\"required\":false,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":50,\"description\":\"Maximum filings to return\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]}]"
)

(utterance-binding research.sec-edgar.fetch-filings :phrases ["get SEC filings" "recent EDGAR filings" "company filings"] :verb research.sec-edgar.fetch-filings)

(verb research.sec-edgar.import-company
  :description "Import SEC company and optionally beneficial owners to database"
  :behavior "plugin"
  :handler "SecImportCompanyOp"
  :effect-class "read_snapshot"
  :flavour "instance_adding"
  :metadata-json "{\"tier\":\"intent\",\"source_of_truth\":\"external\",\"scope\":\"global\",\"writes_operational\":false,\"side_effects\":\"state_write\",\"harm_class\":null,\"action_class\":null,\"noun\":\"entity\",\"internal\":false,\"tags\":[\"write\",\"import\",\"registry-import\"],\"replaces\":null,\"status\":\"active\",\"replaced_by\":null,\"since_version\":null,\"removal_version\":null,\"dangerous\":false,\"subject_kinds\":[],\"phase_tags\":[\"onboarding\"],\"requires_subject\":true,\"produces_focus\":false}"
  :three-axis-json "{\"state_effect\":\"preserving\",\"external_effects\":[\"observational\"],\"consequence\":{\"baseline\":\"benign\",\"escalation\":[]}}"
  :returns-json "{\"type\":\"uuid\",\"name\":\"entity_id\",\"capture\":true}"
  :args-json "[{\"name\":\"cik\",\"type\":\"string\",\"required\":true,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":\"SEC CIK number\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"include-beneficial-owners\",\"type\":\"boolean\",\"required\":false,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":true,\"description\":\"Also import 13D/13G beneficial owners\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"decision-id\",\"type\":\"uuid\",\"required\":false,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":\"Research decision ID for audit trail\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]}]"
)

(utterance-binding research.sec-edgar.import-company :phrases ["import from SEC" "add US company to database" "import EDGAR company"] :verb research.sec-edgar.import-company)

(verb research.sec-edgar.search
  :description "Search SEC EDGAR for companies by name"
  :behavior "plugin"
  :handler "SecSearchOp"
  :effect-class "read_snapshot"
  :flavour "attribute_mutating"
  :metadata-json "{\"tier\":\"diagnostics\",\"source_of_truth\":\"external\",\"scope\":\"global\",\"writes_operational\":false,\"side_effects\":\"facts_only\",\"harm_class\":null,\"action_class\":null,\"noun\":\"company_search_result\",\"internal\":false,\"tags\":[\"read\",\"external-source\",\"registry-lookup\"],\"replaces\":null,\"status\":\"active\",\"replaced_by\":null,\"since_version\":null,\"removal_version\":null,\"dangerous\":false,\"subject_kinds\":[],\"phase_tags\":[\"onboarding\"],\"requires_subject\":true,\"produces_focus\":false}"
  :three-axis-json "{\"state_effect\":\"preserving\",\"external_effects\":[\"observational\"],\"consequence\":{\"baseline\":\"benign\",\"escalation\":[]}}"
  :returns-json "{\"type\":\"record_set\",\"name\":null,\"capture\":null}"
  :args-json "[{\"name\":\"query\",\"type\":\"string\",\"required\":true,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":\"Company name or ticker symbol\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"limit\",\"type\":\"integer\",\"required\":false,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":20,\"description\":\"Maximum results\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]}]"
)

(utterance-binding research.sec-edgar.search :phrases ["search SEC" "find US public company" "look up in EDGAR"] :verb research.sec-edgar.search)

