; Generated by verb_to_dsl from config/verbs/agent.yaml
; DO NOT EDIT — regenerate with `cargo run --bin verb_to_dsl`

(utterance-binding agent :invocation-hints ["start agent" "run autonomously" "agent mode" "research mode" "pause agent" "stop agent" "resume" "continue research"])

(verb agent.activate-teaching
  :domain "agent"
  :description "Activate taught patterns by generating embeddings for semantic search"
  :behavior "plugin"
  :handler "AgentLearnOp"
  :effect-class "read_modify_write"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":\"execute\",\"dangerous\":false,\"harm_class\":\"reversible\",\"internal\":false,\"noun\":\"phrase_embedding\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"global\",\"side_effects\":\"state_write\",\"since_version\":null,\"source_of_truth\":\"operational\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"intent\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"reviewable\",\"escalation\":[]},\"external_effects\":[\"emitting\"],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":false,\"name\":null,\"type\":\"record\"}"
)

(utterance-binding agent.activate-teaching :phrases ["learn" "learn new prompts" "activate taught patterns" "embed taught phrases" "done teaching"] :domain "agent" :verb agent.activate-teaching)

(verb agent.confirm-decision
  :domain "agent"
  :description "Confirm the current checkpoint decision"
  :behavior "plugin"
  :handler "AgentConfirmOp"
  :effect-class "pure"
  :flavour "discretionary"
  :role-guard "{\"any_of\":[\"compliance_admin\",\"senior_compliance\",\"mlro\"]}"
  :audit-class "agent_confirm_decision"
  :metadata-json "{\"action_class\":\"approve\",\"dangerous\":false,\"harm_class\":\"reversible\",\"internal\":false,\"noun\":\"agent_session\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"cbu\",\"side_effects\":\"state_write\",\"since_version\":null,\"source_of_truth\":\"session\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"intent\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"reviewable\",\"escalation\":[]},\"external_effects\":[\"navigating\"],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":null,\"name\":null,\"type\":\"affected\"}"
  :args-json "[{\"default\":null,\"description\":\"Checkpoint to confirm (uses current if not specified)\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":\"checkpoint_id\",\"name\":\"checkpoint-id\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"uuid\",\"valid_values\":null,\"validation\":null},{\"default\":0,\"description\":\"Index of selected candidate (0-based)\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"selected-candidate\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"integer\",\"valid_values\":null,\"validation\":null}]"
)

(utterance-binding agent.confirm-decision :phrases ["confirm decision" "yes, use that one" "proceed with" "that's correct" "accept"] :domain "agent" :verb agent.confirm-decision)

(verb agent.list-tools
  :domain "agent"
  :description "List available MCP tool specifications from the registry"
  :behavior "plugin"
  :handler "AgentListToolsOp"
  :effect-class "read_snapshot"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":\"list\",\"dangerous\":false,\"harm_class\":\"read_only\",\"internal\":false,\"noun\":\"tool_list\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"global\",\"side_effects\":\"facts_only\",\"since_version\":null,\"source_of_truth\":\"operational\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"diagnostics\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"benign\",\"escalation\":[]},\"external_effects\":[\"observational\"],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":false,\"name\":null,\"type\":\"record_set\"}"
  :args-json "[{\"default\":null,\"description\":\"Optional category filter (e.g., registry, taxonomy, planning)\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"category\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"string\",\"valid_values\":null,\"validation\":null}]"
)

(utterance-binding agent.list-tools :phrases ["list tools" "what tools are available" "show available tools" "list MCP tools" "tool inventory" "what tools do you have" "what can you do" "show me all available tools" "which tools are registered" "list all capabilities" "what operations are available" "show tool list" "what commands can I use" "what tools do you have?" "show me your tools" "what are your capabilities" "help me understand what you can do"] :domain "agent" :verb agent.list-tools)

(verb agent.pause
  :domain "agent"
  :description "Pause the running agent loop"
  :behavior "plugin"
  :handler "AgentPauseOp"
  :effect-class "pure"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":\"execute\",\"dangerous\":false,\"harm_class\":\"reversible\",\"internal\":false,\"noun\":\"agent_session\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"cbu\",\"side_effects\":\"state_write\",\"since_version\":null,\"source_of_truth\":\"session\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"intent\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"reviewable\",\"escalation\":[]},\"external_effects\":[\"navigating\"],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":null,\"name\":null,\"type\":\"affected\"}"
)

(utterance-binding agent.pause :phrases ["pause the agent" "pause research" "hold on" "wait"] :domain "agent" :verb agent.pause)

(verb agent.read-history
  :domain "agent"
  :description "Read agent decision and action history for current session"
  :behavior "plugin"
  :handler "AgentHistoryOp"
  :effect-class "read_snapshot"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":\"read\",\"dangerous\":false,\"harm_class\":\"read_only\",\"internal\":false,\"noun\":\"agent_session\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"cbu\",\"side_effects\":\"facts_only\",\"since_version\":null,\"source_of_truth\":\"session\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"intent\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"benign\",\"escalation\":[]},\"external_effects\":[\"observational\"],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":false,\"name\":null,\"type\":\"record\"}"
  :args-json "[{\"default\":50,\"description\":\"Maximum entries to return\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"limit\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"integer\",\"valid_values\":null,\"validation\":null}]"
)

(utterance-binding agent.read-history :phrases ["agent history" "what did the agent do" "show decisions" "show actions"] :domain "agent" :verb agent.read-history)

(verb agent.read-mode
  :domain "agent"
  :description "Read the current agent operating mode (Research or Governed)"
  :behavior "plugin"
  :handler "AgentGetModeOp"
  :effect-class "read_snapshot"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":\"read\",\"dangerous\":false,\"harm_class\":\"read_only\",\"internal\":false,\"noun\":\"agent_mode\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"global\",\"side_effects\":\"facts_only\",\"since_version\":null,\"source_of_truth\":\"operational\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"diagnostics\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"benign\",\"escalation\":[]},\"external_effects\":[\"observational\"],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":false,\"name\":null,\"type\":\"record\"}"
)

(utterance-binding agent.read-mode :phrases ["read agent mode" "what mode am I in" "current agent mode" "show agent mode" "am I in research mode" "am I in governed mode"] :domain "agent" :verb agent.read-mode)

(verb agent.read-policy
  :domain "agent"
  :description "Read the current PolicyGate configuration and active policy snapshot"
  :behavior "plugin"
  :handler "AgentGetPolicyOp"
  :effect-class "read_snapshot"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":\"read\",\"dangerous\":false,\"harm_class\":\"read_only\",\"internal\":false,\"noun\":\"policy_snapshot\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"global\",\"side_effects\":\"facts_only\",\"since_version\":null,\"source_of_truth\":\"operational\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"diagnostics\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"benign\",\"escalation\":[]},\"external_effects\":[\"observational\"],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":false,\"name\":null,\"type\":\"record\"}"
)

(utterance-binding agent.read-policy :phrases ["read policy" "show policy gate" "current policy" "policy configuration" "what policies are active"] :domain "agent" :verb agent.read-policy)

(verb agent.read-status
  :domain "agent"
  :description "Read current agent status"
  :behavior "plugin"
  :handler "AgentStatusOp"
  :effect-class "read_snapshot"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":\"read\",\"dangerous\":false,\"harm_class\":\"read_only\",\"internal\":false,\"noun\":\"agent_session\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"cbu\",\"side_effects\":\"facts_only\",\"since_version\":null,\"source_of_truth\":\"session\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"diagnostics\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"benign\",\"escalation\":[]},\"external_effects\":[\"observational\"],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":false,\"name\":null,\"type\":\"record\"}"
)

(utterance-binding agent.read-status :phrases ["agent status" "what is the agent doing" "research status" "progress" "show agent progress" "what's the agent working on" "how far along is the research" "check agent status" "is the agent still running" "agent progress report"] :domain "agent" :verb agent.read-status)

(verb agent.read-teaching-status
  :domain "agent"
  :description "Read recently taught patterns and their embedding status"
  :behavior "plugin"
  :handler "AgentTeachingStatusOp"
  :effect-class "read_snapshot"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":\"read\",\"dangerous\":false,\"harm_class\":\"read_only\",\"internal\":false,\"noun\":\"phrase_mapping\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"global\",\"side_effects\":\"facts_only\",\"since_version\":null,\"source_of_truth\":\"operational\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"diagnostics\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"benign\",\"escalation\":[]},\"external_effects\":[\"observational\"],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":false,\"name\":null,\"type\":\"record\"}"
  :args-json "[{\"default\":20,\"description\":\"Maximum patterns to return\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"limit\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"integer\",\"valid_values\":null,\"validation\":null},{\"default\":true,\"description\":\"Include aggregate statistics\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"include-stats\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"boolean\",\"valid_values\":null,\"validation\":null}]"
)

(utterance-binding agent.read-teaching-status :phrases ["teaching status" "what have I taught" "show taught phrases" "list learned patterns" "show what the system has learned" "list all taught mappings" "what phrases have been taught" "show learned commands" "teaching history" "review taught patterns"] :domain "agent" :verb agent.read-teaching-status)

(verb agent.read-telemetry-summary
  :domain "agent"
  :description "Read intent event telemetry for hit-rate analysis and pipeline health"
  :behavior "plugin"
  :handler "AgentTelemetrySummaryOp"
  :effect-class "read_snapshot"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":\"read\",\"dangerous\":false,\"harm_class\":\"read_only\",\"internal\":false,\"noun\":\"telemetry_report\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"global\",\"side_effects\":\"facts_only\",\"since_version\":null,\"source_of_truth\":\"operational\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"diagnostics\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"benign\",\"escalation\":[]},\"external_effects\":[\"observational\"],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":false,\"name\":null,\"type\":\"record\"}"
  :args-json "[{\"default\":7,\"description\":\"Number of days to look back\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"days-back\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"integer\",\"valid_values\":null,\"validation\":null},{\"default\":2,\"description\":\"Minimum event count threshold for inclusion\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"min-count\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"integer\",\"valid_values\":null,\"validation\":null},{\"default\":false,\"description\":\"Include CCIR fingerprint and prune statistics\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"include-ccir\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"boolean\",\"valid_values\":null,\"validation\":null}]"
)

(utterance-binding agent.read-telemetry-summary :phrases ["read telemetry summary" "intent telemetry" "show pipeline health" "intent hit rate" "how is the pipeline performing"] :domain "agent" :verb agent.read-telemetry-summary)

(verb agent.reject-decision
  :domain "agent"
  :description "Reject a checkpoint and skip this decision"
  :behavior "plugin"
  :handler "AgentRejectOp"
  :effect-class "pure"
  :flavour "discretionary"
  :role-guard "{\"any_of\":[\"compliance_officer\",\"senior_compliance\",\"mlro\"]}"
  :audit-class "agent_reject_decision"
  :metadata-json "{\"action_class\":\"reject\",\"dangerous\":false,\"harm_class\":\"reversible\",\"internal\":false,\"noun\":\"agent_session\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"cbu\",\"side_effects\":\"state_write\",\"since_version\":null,\"source_of_truth\":\"session\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"intent\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"reviewable\",\"escalation\":[]},\"external_effects\":[\"navigating\"],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":null,\"name\":null,\"type\":\"affected\"}"
  :args-json "[{\"default\":null,\"description\":\"Checkpoint to reject (uses current if not specified)\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":\"checkpoint_id\",\"name\":\"checkpoint-id\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"uuid\",\"valid_values\":null,\"validation\":null},{\"default\":null,\"description\":\"Reason for rejection\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"reason\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"string\",\"valid_values\":null,\"validation\":null}]"
)

(utterance-binding agent.reject-decision :phrases ["reject" "no, skip this" "none of these" "skip"] :domain "agent" :verb agent.reject-decision)

(verb agent.resume
  :domain "agent"
  :description "Resume a paused agent loop"
  :behavior "plugin"
  :handler "AgentResumeOp"
  :effect-class "pure"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":\"execute\",\"dangerous\":false,\"harm_class\":\"reversible\",\"internal\":false,\"noun\":\"agent_session\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"cbu\",\"side_effects\":\"state_write\",\"since_version\":null,\"source_of_truth\":\"session\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"intent\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"reviewable\",\"escalation\":[]},\"external_effects\":[\"navigating\"],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":null,\"name\":null,\"type\":\"affected\"}"
)

(utterance-binding agent.resume :phrases ["resume the agent" "continue research" "keep going" "go ahead"] :domain "agent" :verb agent.resume)

(verb agent.select-decision-option
  :domain "agent"
  :description "Select a specific candidate from checkpoint options"
  :behavior "plugin"
  :handler "AgentSelectOp"
  :effect-class "pure"
  :flavour "discretionary"
  :role-guard "{\"any_of\":[\"compliance_admin\",\"senior_compliance\",\"mlro\"]}"
  :audit-class "agent_select_decision_option"
  :metadata-json "{\"action_class\":\"review\",\"dangerous\":false,\"harm_class\":\"reversible\",\"internal\":false,\"noun\":\"agent_session\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"cbu\",\"side_effects\":\"state_write\",\"since_version\":null,\"source_of_truth\":\"session\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"intent\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"benign\",\"escalation\":[]},\"external_effects\":[\"navigating\"],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":null,\"name\":null,\"type\":\"affected\"}"
  :args-json "[{\"default\":null,\"description\":\"Checkpoint to respond to (uses current if not specified)\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":\"checkpoint_id\",\"name\":\"checkpoint-id\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"uuid\",\"valid_values\":null,\"validation\":null},{\"default\":null,\"description\":\"Index of selected candidate (0-based)\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"candidate-index\",\"preferred_roles\":[],\"required\":true,\"slot_type\":null,\"type\":\"integer\",\"valid_values\":null,\"validation\":null}]"
)

(utterance-binding agent.select-decision-option :phrases ["select option" "use the first one" "use the second one" "pick"] :domain "agent" :verb agent.select-decision-option)

(verb agent.set-authoring-mode
  :domain "agent"
  :description "Set the authoring mode boundary"
  :behavior "plugin"
  :handler "AgentSetAuthoringModeOp"
  :effect-class "read_modify_write"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":\"update\",\"dangerous\":false,\"harm_class\":\"reversible\",\"internal\":false,\"noun\":\"authoring_mode\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"global\",\"side_effects\":\"state_write\",\"since_version\":null,\"source_of_truth\":\"session\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"intent\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"reviewable\",\"escalation\":[]},\"external_effects\":[],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":null,\"name\":null,\"type\":\"affected\"}"
  :args-json "[{\"default\":null,\"description\":\"Authoring mode: research (exploration, ChangeSet authoring,\\nfull schema introspection) or governed (business operations,\\npublish, limited introspection). Default is governed.\\n\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"mode\",\"preferred_roles\":[],\"required\":true,\"slot_type\":null,\"type\":\"string\",\"valid_values\":[\"research\",\"governed\"],\"validation\":null},{\"default\":null,\"description\":\"Explicit confirmation required for mode switch. Must be true\\nto proceed.\\n\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"confirm\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"boolean\",\"valid_values\":null,\"validation\":null}]"
)

(utterance-binding agent.set-authoring-mode :phrases ["switch to research mode" "enter research mode" "switch to governed mode" "enter governed mode" "set authoring mode"] :domain "agent" :verb agent.set-authoring-mode)

(verb agent.set-execution-mode
  :domain "agent"
  :description "Set the agent execution mode"
  :behavior "plugin"
  :handler "AgentSetModeOp"
  :effect-class "read_modify_write"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":\"update\",\"dangerous\":false,\"harm_class\":\"reversible\",\"internal\":false,\"noun\":\"agent_session\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"cbu\",\"side_effects\":\"state_write\",\"since_version\":null,\"source_of_truth\":\"session\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"intent\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"reviewable\",\"escalation\":[]},\"external_effects\":[],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":null,\"name\":null,\"type\":\"affected\"}"
  :args-json "[{\"default\":null,\"description\":\"Mode: manual (no agent), agent (fully autonomous),\\nhybrid (checkpoints on ambiguous)\\n\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"mode\",\"preferred_roles\":[],\"required\":true,\"slot_type\":null,\"type\":\"string\",\"valid_values\":null,\"validation\":null}]"
)

(utterance-binding agent.set-execution-mode :phrases ["set agent mode" "switch to agent mode" "switch to hybrid mode" "change agent operating mode" "go fully autonomous" "enable manual mode" "toggle agent mode" "change to hybrid"] :domain "agent" :verb agent.set-execution-mode)

(verb agent.set-selection-threshold
  :domain "agent"
  :description "Set confidence thresholds for auto-selection"
  :behavior "plugin"
  :handler "AgentSetThresholdOp"
  :effect-class "read_modify_write"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":\"update\",\"dangerous\":false,\"harm_class\":\"reversible\",\"internal\":false,\"noun\":\"agent_session\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"cbu\",\"side_effects\":\"state_write\",\"since_version\":null,\"source_of_truth\":\"session\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"intent\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"reviewable\",\"escalation\":[]},\"external_effects\":[],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":null,\"name\":null,\"type\":\"affected\"}"
  :args-json "[{\"default\":null,\"description\":\"Confidence threshold for auto-proceed (default 0.90)\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"auto-proceed\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"decimal\",\"valid_values\":null,\"validation\":null},{\"default\":null,\"description\":\"Minimum confidence for checkpoint (default 0.70)\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"ambiguous-floor\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"decimal\",\"valid_values\":null,\"validation\":null}]"
)

(utterance-binding agent.set-selection-threshold :phrases ["set confidence threshold" "adjust auto-proceed threshold" "change agent threshold" "configure confidence level" "set ambiguity floor" "tune matching sensitivity" "adjust selection threshold" "modify confidence settings"] :domain "agent" :verb agent.set-selection-threshold)

(verb agent.start
  :domain "agent"
  :description "Start agent mode with a specific task"
  :behavior "plugin"
  :handler "AgentStartOp"
  :effect-class "pure"
  :flavour "instance_adding"
  :metadata-json "{\"action_class\":\"execute\",\"dangerous\":false,\"harm_class\":\"reversible\",\"internal\":false,\"noun\":\"agent_session\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"cbu\",\"side_effects\":\"state_write\",\"since_version\":null,\"source_of_truth\":\"session\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"intent\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"reviewable\",\"escalation\":[]},\"external_effects\":[\"navigating\"],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":true,\"name\":\"agent_session_id\",\"type\":\"uuid\"}"
  :args-json "[{\"default\":null,\"description\":\"Task type: resolve-gaps, chain-research, enrich-entity,\\nenrich-group, screen-entities\\n\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"task\",\"preferred_roles\":[],\"required\":true,\"slot_type\":null,\"type\":\"string\",\"valid_values\":null,\"validation\":null},{\"default\":null,\"description\":\"Target entity for the task (if applicable)\",\"fuzzy_check\":null,\"lookup\":{\"entity_type\":\"entity\",\"primary_key\":\"entity_id\",\"resolution_mode\":null,\"role_filter\":null,\"schema\":\"ob-poc\",\"scope_key\":null,\"search_key\":\"name\",\"table\":\"entities\"},\"maps_to\":\"target_entity_id\",\"name\":\"entity-id\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"uuid\",\"valid_values\":null,\"validation\":null},{\"default\":50,\"description\":\"Maximum loop iterations before stopping\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"max-iterations\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"integer\",\"valid_values\":null,\"validation\":null},{\"default\":\"hybrid\",\"description\":\"Agent mode: agent (fully autonomous), hybrid (checkpoints on ambiguous)\\n\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"mode\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"string\",\"valid_values\":null,\"validation\":null}]"
)

(utterance-binding agent.start :phrases ["start the agent" "run research automatically" "start autonomous mode" "resolve gaps for" "enrich"] :domain "agent" :verb agent.start)

(verb agent.stop
  :domain "agent"
  :description "Stop the agent loop completely"
  :behavior "plugin"
  :handler "AgentStopOp"
  :effect-class "pure"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":\"execute\",\"dangerous\":false,\"harm_class\":\"reversible\",\"internal\":false,\"noun\":\"agent_session\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"cbu\",\"side_effects\":\"state_write\",\"since_version\":null,\"source_of_truth\":\"session\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"intent\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"reviewable\",\"escalation\":[]},\"external_effects\":[\"navigating\"],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":null,\"name\":null,\"type\":\"affected\"}"
)

(utterance-binding agent.stop :phrases ["stop the agent" "cancel research" "abort" "stop"] :domain "agent" :verb agent.stop)

(verb agent.teach
  :domain "agent"
  :description "Teach a phrase→verb mapping to improve intent recognition"
  :behavior "plugin"
  :handler "AgentTeachOp"
  :effect-class "read_modify_write"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":\"create\",\"dangerous\":false,\"harm_class\":\"reversible\",\"internal\":false,\"noun\":\"phrase_mapping\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"global\",\"side_effects\":\"state_write\",\"since_version\":null,\"source_of_truth\":\"operational\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"intent\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"reviewable\",\"escalation\":[]},\"external_effects\":[\"emitting\"],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":false,\"name\":null,\"type\":\"record\"}"
  :args-json "[{\"default\":null,\"description\":\"The phrase to teach (will be normalized)\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"phrase\",\"preferred_roles\":[],\"required\":true,\"slot_type\":null,\"type\":\"string\",\"valid_values\":null,\"validation\":null},{\"default\":null,\"description\":\"The DSL verb it should trigger (e.g., 'cbu.create')\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"verb\",\"preferred_roles\":[],\"required\":true,\"slot_type\":null,\"type\":\"string\",\"valid_values\":null,\"validation\":null},{\"default\":\"dsl_teaching\",\"description\":\"Source identifier for audit trail\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"source\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"string\",\"valid_values\":null,\"validation\":null}]"
)

(utterance-binding agent.teach :phrases ["teach the system" "learn this phrase" "remember this mapping" "when I say X do Y" "teach the system that spin up means create CBU" "train the system to recognise this phrase" "add a new phrase mapping" "teach it that this phrase means this verb" "map this phrase to a verb" "teach the agent a new command" "I want to teach you a shortcut" "associate this phrase with a verb"] :domain "agent" :verb agent.teach)

(verb agent.unteach
  :domain "agent"
  :description "Remove a previously taught phrase→verb mapping"
  :behavior "plugin"
  :handler "AgentUnteachOp"
  :effect-class "read_modify_write"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":\"remove\",\"dangerous\":false,\"harm_class\":\"reversible\",\"internal\":false,\"noun\":\"phrase_mapping\",\"phase_tags\":[\"navigation\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"global\",\"side_effects\":\"state_write\",\"since_version\":null,\"source_of_truth\":\"operational\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[],\"tier\":\"intent\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"reviewable\",\"escalation\":[]},\"external_effects\":[\"emitting\"],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":false,\"name\":null,\"type\":\"record\"}"
  :args-json "[{\"default\":null,\"description\":\"The phrase to remove\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"phrase\",\"preferred_roles\":[],\"required\":true,\"slot_type\":null,\"type\":\"string\",\"valid_values\":null,\"validation\":null},{\"default\":null,\"description\":\"The verb it was mapped to (optional, removes all if not specified)\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"verb\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"string\",\"valid_values\":null,\"validation\":null},{\"default\":\"dsl_unteach\",\"description\":\"Reason for removal (for audit)\",\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":null,\"name\":\"reason\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"string\",\"valid_values\":null,\"validation\":null}]"
)

(utterance-binding agent.unteach :phrases ["unteach" "forget this phrase" "remove this mapping" "unlearn" "unteach this phrase" "remove a taught phrase" "delete a phrase mapping" "forget this command" "undo a teaching" "remove a learned pattern"] :domain "agent" :verb agent.unteach)
