; Generated by verb_to_dsl from config/verbs/application-instance.yaml
; DO NOT EDIT — regenerate with `cargo run --bin verb_to_dsl`

(utterance-binding application-instance :invocation-hints ["application instance" "app instance" "BNY system instance" "deployment"])

; Pattern D: transition_args present — see docs/verb-redesigns/
(verb application-instance.activate
  :description "Activate a provisioned (or offline / maintenance) instance — transition to ACTIVE"
  :behavior "crud"
  :effect-class "read_modify_write"
  :flavour "attribute_mutating"
  :metadata-json "{\"tier\":\"intent\",\"source_of_truth\":\"operational\",\"scope\":\"global\",\"writes_operational\":false,\"side_effects\":\"state_write\",\"harm_class\":null,\"action_class\":null,\"noun\":\"application_instance\",\"internal\":false,\"tags\":[\"lifecycle\",\"write\",\"platform\"],\"replaces\":null,\"status\":\"active\",\"replaced_by\":null,\"since_version\":null,\"removal_version\":null,\"dangerous\":false,\"subject_kinds\":[],\"phase_tags\":[\"lifecycle_resources\"],\"requires_subject\":true,\"produces_focus\":false}"
  :three-axis-json "{\"state_effect\":\"transition\",\"external_effects\":[\"emitting\"],\"consequence\":{\"baseline\":\"reviewable\",\"escalation\":[]}}"
  :transition-args-json "{\"entity_id_arg\":\"instance-id\",\"target_workspace\":\"lifecycle_resources\",\"target_slot\":\"application_instance\"}"
  :lifecycle-json "{\"entity_arg\":\"instance-id\",\"requires_states\":[\"PROVISIONED\"],\"transitions_to\":null,\"transitions_to_arg\":null,\"precondition_checks\":[],\"writes_tables\":[],\"reads_tables\":[]}"
  :returns-json "{\"type\":\"affected\",\"name\":null,\"capture\":null}"
  :args-json "[{\"name\":\"instance-id\",\"type\":\"uuid\",\"required\":true,\"maps_to\":\"id\",\"lookup\":{\"table\":\"application_instances\",\"schema\":\"ob-poc\",\"entity_type\":\"application_instance\",\"search_key\":\"instance_label\",\"primary_key\":\"id\",\"resolution_mode\":null,\"scope_key\":null,\"role_filter\":null},\"valid_values\":null,\"default\":null,\"description\":null,\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]}]"
  :crud-json "{\"operation\":\"update\",\"table\":\"application_instances\",\"schema\":\"ob-poc\",\"key\":\"id\",\"returning\":null,\"conflict_keys\":null,\"conflict_constraint\":null,\"junction\":null,\"from_col\":null,\"to_col\":null,\"role_table\":null,\"role_col\":null,\"fk_col\":null,\"filter_col\":null,\"primary_table\":null,\"join_table\":null,\"join_col\":null,\"base_table\":null,\"extension_table\":null,\"extension_table_column\":null,\"type_id_column\":null,\"type_code\":null,\"order_by\":null,\"set_values\":{\"lifecycle_status\":\"ACTIVE\"}}"
)

(utterance-binding application-instance.activate :phrases ["activate application instance" "activate app instance" "bring instance live" "make instance active" "start serving from instance"] :verb application-instance.activate)

; Pattern D: transition_args present — see docs/verb-redesigns/
(verb application-instance.bring-online
  :description "Bring an OFFLINE instance back to ACTIVE"
  :behavior "crud"
  :effect-class "read_modify_write"
  :flavour "attribute_mutating"
  :metadata-json "{\"tier\":\"intent\",\"source_of_truth\":\"operational\",\"scope\":\"global\",\"writes_operational\":false,\"side_effects\":\"state_write\",\"harm_class\":null,\"action_class\":null,\"noun\":\"application_instance\",\"internal\":false,\"tags\":[\"lifecycle\",\"write\",\"platform\"],\"replaces\":null,\"status\":\"active\",\"replaced_by\":null,\"since_version\":null,\"removal_version\":null,\"dangerous\":false,\"subject_kinds\":[],\"phase_tags\":[\"lifecycle_resources\"],\"requires_subject\":true,\"produces_focus\":false}"
  :three-axis-json "{\"state_effect\":\"transition\",\"external_effects\":[\"emitting\"],\"consequence\":{\"baseline\":\"reviewable\",\"escalation\":[]}}"
  :transition-args-json "{\"entity_id_arg\":\"instance-id\",\"target_workspace\":\"lifecycle_resources\",\"target_slot\":\"application_instance\"}"
  :lifecycle-json "{\"entity_arg\":\"instance-id\",\"requires_states\":[\"OFFLINE\"],\"transitions_to\":null,\"transitions_to_arg\":null,\"precondition_checks\":[],\"writes_tables\":[],\"reads_tables\":[]}"
  :returns-json "{\"type\":\"affected\",\"name\":null,\"capture\":null}"
  :args-json "[{\"name\":\"instance-id\",\"type\":\"uuid\",\"required\":true,\"maps_to\":\"id\",\"lookup\":{\"table\":\"application_instances\",\"schema\":\"ob-poc\",\"entity_type\":\"application_instance\",\"search_key\":\"instance_label\",\"primary_key\":\"id\",\"resolution_mode\":null,\"scope_key\":null,\"role_filter\":null},\"valid_values\":null,\"default\":null,\"description\":null,\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]}]"
  :crud-json "{\"operation\":\"update\",\"table\":\"application_instances\",\"schema\":\"ob-poc\",\"key\":\"id\",\"returning\":null,\"conflict_keys\":null,\"conflict_constraint\":null,\"junction\":null,\"from_col\":null,\"to_col\":null,\"role_table\":null,\"role_col\":null,\"fk_col\":null,\"filter_col\":null,\"primary_table\":null,\"join_table\":null,\"join_col\":null,\"base_table\":null,\"extension_table\":null,\"extension_table_column\":null,\"type_id_column\":null,\"type_code\":null,\"order_by\":null,\"set_values\":{\"lifecycle_status\":\"ACTIVE\"}}"
)

(utterance-binding application-instance.bring-online :phrases ["bring instance online" "online application instance" "restart instance" "resume offline instance" "lift offline hold"] :verb application-instance.bring-online)

; Pattern D: transition_args present — see docs/verb-redesigns/
(verb application-instance.decommission
  :description "Decommission an instance — terminal transition; cascades bindings to RETIRED"
  :behavior "crud"
  :effect-class "read_modify_write"
  :flavour "discretionary"
  :role-guard "{\"any_of\":[\"compliance_officer\",\"senior_compliance\",\"mlro\"]}"
  :audit-class "application_instance_decommission"
  :metadata-json "{\"tier\":\"intent\",\"source_of_truth\":\"operational\",\"scope\":\"global\",\"writes_operational\":false,\"side_effects\":\"state_write\",\"harm_class\":null,\"action_class\":null,\"noun\":\"application_instance\",\"internal\":false,\"tags\":[\"lifecycle\",\"write\",\"destructive\",\"platform\"],\"replaces\":null,\"status\":\"active\",\"replaced_by\":null,\"since_version\":null,\"removal_version\":null,\"dangerous\":false,\"subject_kinds\":[],\"phase_tags\":[\"lifecycle_resources\"],\"requires_subject\":true,\"produces_focus\":false}"
  :three-axis-json "{\"state_effect\":\"transition\",\"external_effects\":[\"emitting\"],\"consequence\":{\"baseline\":\"requires_explicit_authorisation\",\"escalation\":[]}}"
  :transition-args-json "{\"entity_id_arg\":\"instance-id\",\"target_workspace\":\"lifecycle_resources\",\"target_slot\":\"application_instance\"}"
  :lifecycle-json "{\"entity_arg\":\"instance-id\",\"requires_states\":[\"ACTIVE\",\"OFFLINE\",\"MAINTENANCE_WINDOW\",\"DEGRADED\"],\"transitions_to\":null,\"transitions_to_arg\":null,\"precondition_checks\":[],\"writes_tables\":[],\"reads_tables\":[]}"
  :returns-json "{\"type\":\"affected\",\"name\":null,\"capture\":null}"
  :args-json "[{\"name\":\"instance-id\",\"type\":\"uuid\",\"required\":true,\"maps_to\":\"id\",\"lookup\":{\"table\":\"application_instances\",\"schema\":\"ob-poc\",\"entity_type\":\"application_instance\",\"search_key\":\"instance_label\",\"primary_key\":\"id\",\"resolution_mode\":null,\"scope_key\":null,\"role_filter\":null},\"valid_values\":null,\"default\":null,\"description\":null,\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"reason\",\"type\":\"string\",\"required\":true,\"maps_to\":\"notes\",\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":null,\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]}]"
  :crud-json "{\"operation\":\"update\",\"table\":\"application_instances\",\"schema\":\"ob-poc\",\"key\":\"id\",\"returning\":null,\"conflict_keys\":null,\"conflict_constraint\":null,\"junction\":null,\"from_col\":null,\"to_col\":null,\"role_table\":null,\"role_col\":null,\"fk_col\":null,\"filter_col\":null,\"primary_table\":null,\"join_table\":null,\"join_col\":null,\"base_table\":null,\"extension_table\":null,\"extension_table_column\":null,\"type_id_column\":null,\"type_code\":null,\"order_by\":null,\"set_values\":{\"decommissioned_at\":\"now()\",\"lifecycle_status\":\"DECOMMISSIONED\"}}"
)

(utterance-binding application-instance.decommission :phrases ["decommission application instance" "retire application instance" "decommission app instance" "permanently retire instance" "sunset application instance"] :verb application-instance.decommission)

; Pattern D: transition_args present — see docs/verb-redesigns/
(verb application-instance.enter-maintenance
  :description "Enter maintenance window — pause traffic without retiring bindings"
  :behavior "crud"
  :effect-class "read_modify_write"
  :flavour "attribute_mutating"
  :metadata-json "{\"tier\":\"intent\",\"source_of_truth\":\"operational\",\"scope\":\"global\",\"writes_operational\":false,\"side_effects\":\"state_write\",\"harm_class\":null,\"action_class\":null,\"noun\":\"application_instance\",\"internal\":false,\"tags\":[\"lifecycle\",\"write\",\"platform\"],\"replaces\":null,\"status\":\"active\",\"replaced_by\":null,\"since_version\":null,\"removal_version\":null,\"dangerous\":false,\"subject_kinds\":[],\"phase_tags\":[\"lifecycle_resources\"],\"requires_subject\":true,\"produces_focus\":false}"
  :three-axis-json "{\"state_effect\":\"transition\",\"external_effects\":[\"emitting\"],\"consequence\":{\"baseline\":\"requires_confirmation\",\"escalation\":[]}}"
  :transition-args-json "{\"entity_id_arg\":\"instance-id\",\"target_workspace\":\"lifecycle_resources\",\"target_slot\":\"application_instance\"}"
  :lifecycle-json "{\"entity_arg\":\"instance-id\",\"requires_states\":[\"ACTIVE\"],\"transitions_to\":null,\"transitions_to_arg\":null,\"precondition_checks\":[],\"writes_tables\":[],\"reads_tables\":[]}"
  :returns-json "{\"type\":\"affected\",\"name\":null,\"capture\":null}"
  :args-json "[{\"name\":\"instance-id\",\"type\":\"uuid\",\"required\":true,\"maps_to\":\"id\",\"lookup\":{\"table\":\"application_instances\",\"schema\":\"ob-poc\",\"entity_type\":\"application_instance\",\"search_key\":\"instance_label\",\"primary_key\":\"id\",\"resolution_mode\":null,\"scope_key\":null,\"role_filter\":null},\"valid_values\":null,\"default\":null,\"description\":null,\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"reason\",\"type\":\"string\",\"required\":false,\"maps_to\":\"notes\",\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":null,\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]}]"
  :crud-json "{\"operation\":\"update\",\"table\":\"application_instances\",\"schema\":\"ob-poc\",\"key\":\"id\",\"returning\":null,\"conflict_keys\":null,\"conflict_constraint\":null,\"junction\":null,\"from_col\":null,\"to_col\":null,\"role_table\":null,\"role_col\":null,\"fk_col\":null,\"filter_col\":null,\"primary_table\":null,\"join_table\":null,\"join_col\":null,\"base_table\":null,\"extension_table\":null,\"extension_table_column\":null,\"type_id_column\":null,\"type_code\":null,\"order_by\":null,\"set_values\":{\"lifecycle_status\":\"MAINTENANCE_WINDOW\"}}"
)

(utterance-binding application-instance.enter-maintenance :phrases ["enter maintenance window" "begin maintenance" "pause instance for maintenance" "schedule maintenance window" "put instance into maintenance"] :verb application-instance.enter-maintenance)

; Pattern D: transition_args present — see docs/verb-redesigns/
(verb application-instance.exit-maintenance
  :description "Exit maintenance window — return instance to ACTIVE"
  :behavior "crud"
  :effect-class "read_modify_write"
  :flavour "attribute_mutating"
  :metadata-json "{\"tier\":\"intent\",\"source_of_truth\":\"operational\",\"scope\":\"global\",\"writes_operational\":false,\"side_effects\":\"state_write\",\"harm_class\":null,\"action_class\":null,\"noun\":\"application_instance\",\"internal\":false,\"tags\":[\"lifecycle\",\"write\",\"platform\"],\"replaces\":null,\"status\":\"active\",\"replaced_by\":null,\"since_version\":null,\"removal_version\":null,\"dangerous\":false,\"subject_kinds\":[],\"phase_tags\":[\"lifecycle_resources\"],\"requires_subject\":true,\"produces_focus\":false}"
  :three-axis-json "{\"state_effect\":\"transition\",\"external_effects\":[\"emitting\"],\"consequence\":{\"baseline\":\"reviewable\",\"escalation\":[]}}"
  :transition-args-json "{\"entity_id_arg\":\"instance-id\",\"target_workspace\":\"lifecycle_resources\",\"target_slot\":\"application_instance\"}"
  :lifecycle-json "{\"entity_arg\":\"instance-id\",\"requires_states\":[\"MAINTENANCE_WINDOW\"],\"transitions_to\":null,\"transitions_to_arg\":null,\"precondition_checks\":[],\"writes_tables\":[],\"reads_tables\":[]}"
  :returns-json "{\"type\":\"affected\",\"name\":null,\"capture\":null}"
  :args-json "[{\"name\":\"instance-id\",\"type\":\"uuid\",\"required\":true,\"maps_to\":\"id\",\"lookup\":{\"table\":\"application_instances\",\"schema\":\"ob-poc\",\"entity_type\":\"application_instance\",\"search_key\":\"instance_label\",\"primary_key\":\"id\",\"resolution_mode\":null,\"scope_key\":null,\"role_filter\":null},\"valid_values\":null,\"default\":null,\"description\":null,\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]}]"
  :crud-json "{\"operation\":\"update\",\"table\":\"application_instances\",\"schema\":\"ob-poc\",\"key\":\"id\",\"returning\":null,\"conflict_keys\":null,\"conflict_constraint\":null,\"junction\":null,\"from_col\":null,\"to_col\":null,\"role_table\":null,\"role_col\":null,\"fk_col\":null,\"filter_col\":null,\"primary_table\":null,\"join_table\":null,\"join_col\":null,\"base_table\":null,\"extension_table\":null,\"extension_table_column\":null,\"type_id_column\":null,\"type_code\":null,\"order_by\":null,\"set_values\":{\"lifecycle_status\":\"ACTIVE\"}}"
)

(utterance-binding application-instance.exit-maintenance :phrases ["exit maintenance window" "end maintenance" "complete maintenance" "restore instance after maintenance" "resume from maintenance"] :verb application-instance.exit-maintenance)

(verb application-instance.provision
  :description "Provision a new application instance (creates row in PROVISIONED state)"
  :behavior "crud"
  :effect-class "append_fact"
  :flavour "instance_adding"
  :metadata-json "{\"tier\":\"intent\",\"source_of_truth\":\"operational\",\"scope\":\"global\",\"writes_operational\":false,\"side_effects\":\"state_write\",\"harm_class\":null,\"action_class\":null,\"noun\":\"application_instance\",\"internal\":false,\"tags\":[\"lifecycle\",\"write\",\"platform\"],\"replaces\":null,\"status\":\"active\",\"replaced_by\":null,\"since_version\":null,\"removal_version\":null,\"dangerous\":false,\"subject_kinds\":[],\"phase_tags\":[\"lifecycle_resources\"],\"requires_subject\":true,\"produces_focus\":false}"
  :three-axis-json "{\"state_effect\":\"preserving\",\"external_effects\":[],\"consequence\":{\"baseline\":\"reviewable\",\"escalation\":[]}}"
  :returns-json "{\"type\":\"uuid\",\"name\":\"id\",\"capture\":true}"
  :args-json "[{\"name\":\"application-id\",\"type\":\"uuid\",\"required\":true,\"maps_to\":\"application_id\",\"lookup\":{\"table\":\"applications\",\"schema\":\"ob-poc\",\"entity_type\":\"application\",\"search_key\":\"name\",\"primary_key\":\"id\",\"resolution_mode\":null,\"scope_key\":null,\"role_filter\":null},\"valid_values\":null,\"default\":null,\"description\":null,\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"environment\",\"type\":\"string\",\"required\":true,\"maps_to\":\"environment\",\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":\"Deployment environment (prod-eu, prod-us, uat, dev)\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"instance-label\",\"type\":\"string\",\"required\":true,\"maps_to\":\"instance_label\",\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":\"Instance label (e.g. CCC-Settlement-2.7-prod-eu)\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"notes\",\"type\":\"string\",\"required\":false,\"maps_to\":\"notes\",\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":null,\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]}]"
  :crud-json "{\"operation\":\"insert\",\"table\":\"application_instances\",\"schema\":\"ob-poc\",\"key\":null,\"returning\":\"id\",\"conflict_keys\":null,\"conflict_constraint\":null,\"junction\":null,\"from_col\":null,\"to_col\":null,\"role_table\":null,\"role_col\":null,\"fk_col\":null,\"filter_col\":null,\"primary_table\":null,\"join_table\":null,\"join_col\":null,\"base_table\":null,\"extension_table\":null,\"extension_table_column\":null,\"type_id_column\":null,\"type_code\":null,\"order_by\":null,\"set_values\":null}"
)

(utterance-binding application-instance.provision :phrases ["provision application instance" "provision app instance" "deploy application instance" "create application instance" "set up new instance" "spin up application instance"] :verb application-instance.provision)

; Pattern D: transition_args present — see docs/verb-redesigns/
(verb application-instance.take-offline
  :description "Take instance OFFLINE (operational hold — incident, security freeze, capacity action)"
  :behavior "crud"
  :effect-class "read_modify_write"
  :flavour "attribute_mutating"
  :metadata-json "{\"tier\":\"intent\",\"source_of_truth\":\"operational\",\"scope\":\"global\",\"writes_operational\":false,\"side_effects\":\"state_write\",\"harm_class\":null,\"action_class\":null,\"noun\":\"application_instance\",\"internal\":false,\"tags\":[\"lifecycle\",\"write\",\"platform\"],\"replaces\":null,\"status\":\"active\",\"replaced_by\":null,\"since_version\":null,\"removal_version\":null,\"dangerous\":false,\"subject_kinds\":[],\"phase_tags\":[\"lifecycle_resources\"],\"requires_subject\":true,\"produces_focus\":false}"
  :three-axis-json "{\"state_effect\":\"transition\",\"external_effects\":[\"emitting\"],\"consequence\":{\"baseline\":\"requires_confirmation\",\"escalation\":[]}}"
  :transition-args-json "{\"entity_id_arg\":\"instance-id\",\"target_workspace\":\"lifecycle_resources\",\"target_slot\":\"application_instance\"}"
  :lifecycle-json "{\"entity_arg\":\"instance-id\",\"requires_states\":[\"ACTIVE\"],\"transitions_to\":null,\"transitions_to_arg\":null,\"precondition_checks\":[],\"writes_tables\":[],\"reads_tables\":[]}"
  :returns-json "{\"type\":\"affected\",\"name\":null,\"capture\":null}"
  :args-json "[{\"name\":\"instance-id\",\"type\":\"uuid\",\"required\":true,\"maps_to\":\"id\",\"lookup\":{\"table\":\"application_instances\",\"schema\":\"ob-poc\",\"entity_type\":\"application_instance\",\"search_key\":\"instance_label\",\"primary_key\":\"id\",\"resolution_mode\":null,\"scope_key\":null,\"role_filter\":null},\"valid_values\":null,\"default\":null,\"description\":null,\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"reason\",\"type\":\"string\",\"required\":true,\"maps_to\":\"notes\",\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":null,\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]}]"
  :crud-json "{\"operation\":\"update\",\"table\":\"application_instances\",\"schema\":\"ob-poc\",\"key\":\"id\",\"returning\":null,\"conflict_keys\":null,\"conflict_constraint\":null,\"junction\":null,\"from_col\":null,\"to_col\":null,\"role_table\":null,\"role_col\":null,\"fk_col\":null,\"filter_col\":null,\"primary_table\":null,\"join_table\":null,\"join_col\":null,\"base_table\":null,\"extension_table\":null,\"extension_table_column\":null,\"type_id_column\":null,\"type_code\":null,\"order_by\":null,\"set_values\":{\"lifecycle_status\":\"OFFLINE\"}}"
)

(utterance-binding application-instance.take-offline :phrases ["take instance offline" "offline application instance" "halt instance traffic" "stop serving from instance" "operational hold on instance"] :verb application-instance.take-offline)

