; Generated by verb_to_dsl from config/verbs/service-option.yaml
; DO NOT EDIT — regenerate with `cargo run --bin verb_to_dsl`

(verb service-option.list-by-service
  :description "List option definitions for a service version"
  :behavior "plugin"
  :effect-class "read_snapshot"
  :flavour "attribute_mutating"
  :metadata-json "{\"tier\":\"reference\",\"source_of_truth\":\"catalog\",\"scope\":\"global\",\"writes_operational\":false,\"side_effects\":\"facts_only\",\"harm_class\":null,\"action_class\":null,\"noun\":\"service_option\",\"internal\":false,\"tags\":[\"service-options\",\"catalogue\",\"read\"],\"replaces\":null,\"status\":\"active\",\"replaced_by\":null,\"since_version\":null,\"removal_version\":null,\"dangerous\":false,\"subject_kinds\":[\"service-option\"],\"phase_tags\":[\"service-options\"],\"requires_subject\":true,\"produces_focus\":false}"
  :three-axis-json "{\"state_effect\":\"preserving\",\"external_effects\":[\"observational\"],\"consequence\":{\"baseline\":\"benign\",\"escalation\":[]}}"
  :returns-json "{\"type\":\"record_set\",\"name\":null,\"capture\":null}"
  :args-json "[{\"name\":\"service-id\",\"type\":\"uuid\",\"required\":false,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":null,\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"service\",\"type\":\"string\",\"required\":false,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":null,\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"service-version-id\",\"type\":\"uuid\",\"required\":false,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":null,\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]}]"
)

(utterance-binding service-option.list-by-service :phrases ["show service options" "list options for service" "show custody settlement options"] :verb service-option.list-by-service)

(verb service-option.read
  :description "Read one service option definition"
  :behavior "plugin"
  :effect-class "read_snapshot"
  :flavour "attribute_mutating"
  :metadata-json "{\"tier\":\"reference\",\"source_of_truth\":\"catalog\",\"scope\":\"global\",\"writes_operational\":false,\"side_effects\":\"facts_only\",\"harm_class\":null,\"action_class\":null,\"noun\":\"service_option\",\"internal\":false,\"tags\":[\"service-options\",\"catalogue\",\"read\"],\"replaces\":null,\"status\":\"active\",\"replaced_by\":null,\"since_version\":null,\"removal_version\":null,\"dangerous\":false,\"subject_kinds\":[\"service-option\"],\"phase_tags\":[\"service-options\"],\"requires_subject\":true,\"produces_focus\":false}"
  :three-axis-json "{\"state_effect\":\"preserving\",\"external_effects\":[\"observational\"],\"consequence\":{\"baseline\":\"benign\",\"escalation\":[]}}"
  :returns-json "{\"type\":\"record\",\"name\":null,\"capture\":null}"
  :args-json "[{\"name\":\"service-option-def-id\",\"type\":\"uuid\",\"required\":false,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":null,\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"service-id\",\"type\":\"uuid\",\"required\":false,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":null,\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"service\",\"type\":\"string\",\"required\":false,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":null,\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"option-key\",\"type\":\"string\",\"required\":false,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":null,\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]}]"
)

(utterance-binding service-option.read :phrases ["read service option" "inspect service option" "show option definition"] :verb service-option.read)

