; Generated by verb_to_dsl from config/verbs/workflow-start-process.yaml
; DO NOT EDIT — regenerate with `cargo run --bin verb_to_dsl`

(verb workflow.start-process
  :description "Start a named BPMN process instance and run it to quiescence.\nIf the process immediately parks at a dsl.form human task, the\nresponse contains a bpmn_form payload for the cockpit to render.\n"
  :behavior "plugin"
  :flavour "instance_adding"
  :metadata-json "{\"tier\":\"intent\",\"source_of_truth\":\"external\",\"scope\":null,\"writes_operational\":false,\"side_effects\":\"state_write\",\"harm_class\":null,\"action_class\":null,\"noun\":null,\"internal\":false,\"tags\":[],\"replaces\":null,\"status\":\"active\",\"replaced_by\":null,\"since_version\":null,\"removal_version\":null,\"dangerous\":false,\"subject_kinds\":[],\"phase_tags\":[\"workflow\"],\"requires_subject\":true,\"produces_focus\":false}"
  :three-axis-json "{\"state_effect\":\"preserving\",\"external_effects\":[\"emitting\"],\"consequence\":{\"baseline\":\"reviewable\",\"escalation\":[]}}"
  :returns-json "{\"type\":\"record\",\"name\":null,\"capture\":null}"
  :args-json "[{\"name\":\"process_name\",\"type\":\"string\",\"required\":true,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":\"Name of the process definition (matches process_definitions.name)\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]},{\"name\":\"initial_data\",\"type\":\"object\",\"required\":false,\"maps_to\":null,\"lookup\":null,\"valid_values\":null,\"default\":null,\"description\":\"Initial data to inject into the process instance\",\"validation\":null,\"fuzzy_check\":null,\"slot_type\":null,\"preferred_roles\":[]}]"
)

