; Generated by verb_to_dsl from config/verbs/kyc/kyc.yaml
; DO NOT EDIT — regenerate with `cargo run --bin verb_to_dsl`

(verb kyc.case-status
  :domain "kyc"
  :description "Check the status of a KYC case"
  :behavior "crud"
  :effect-class "read_snapshot"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":null,\"dangerous\":false,\"harm_class\":null,\"internal\":false,\"noun\":\"kyc_case\",\"phase_tags\":[\"kyc\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"cbu\",\"side_effects\":\"facts_only\",\"since_version\":null,\"source_of_truth\":\"workflow\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[\"kyc\"],\"tier\":\"intent\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"benign\",\"escalation\":[]},\"external_effects\":[],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":null,\"name\":null,\"type\":\"record_set\"}"
  :args-json "[{\"default\":null,\"description\":null,\"fuzzy_check\":null,\"lookup\":{\"entity_type\":\"kyc_case\",\"primary_key\":\"case_id\",\"resolution_mode\":null,\"role_filter\":null,\"schema\":\"ob-poc\",\"scope_key\":null,\"search_key\":\"case_id\",\"table\":\"cases\"},\"maps_to\":\"case_id\",\"name\":\"case-id\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"uuid\",\"valid_values\":null,\"validation\":null}]"
  :crud-json "{\"base_table\":null,\"conflict_constraint\":null,\"conflict_keys\":null,\"extension_table\":null,\"extension_table_column\":null,\"filter_col\":null,\"fk_col\":null,\"from_col\":null,\"join_col\":null,\"join_table\":null,\"junction\":null,\"key\":null,\"operation\":\"select\",\"order_by\":null,\"primary_table\":null,\"returning\":null,\"role_col\":null,\"role_table\":null,\"schema\":\"ob-poc\",\"set_values\":null,\"table\":\"cases\",\"to_col\":null,\"type_code\":null,\"type_id_column\":null}"
)

(utterance-binding kyc.case-status :phrases ["what is the KYC status for this client?" "check KYC status" "what is the KYC status" "KYC status for client" "show KYC status" "what is the KYC status for this CBU"] :domain "kyc" :verb kyc.case-status)

(verb kyc.list-missing-items
  :domain "kyc"
  :description "List missing information before KYC sign-off"
  :behavior "crud"
  :effect-class "read_snapshot"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":null,\"dangerous\":false,\"harm_class\":null,\"internal\":false,\"noun\":\"missing_documents\",\"phase_tags\":[\"kyc\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"cbu\",\"side_effects\":\"facts_only\",\"since_version\":null,\"source_of_truth\":\"workflow\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[\"read\",\"query\",\"workflow\"],\"tier\":\"intent\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"benign\",\"escalation\":[]},\"external_effects\":[],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":null,\"name\":null,\"type\":\"record_set\"}"
  :args-json "[{\"default\":null,\"description\":null,\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":\"subject_entity_id\",\"name\":\"entity-id\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"uuid\",\"valid_values\":null,\"validation\":null}]"
  :crud-json "{\"base_table\":null,\"conflict_constraint\":null,\"conflict_keys\":null,\"extension_table\":null,\"extension_table_column\":null,\"filter_col\":null,\"fk_col\":null,\"from_col\":null,\"join_col\":null,\"join_table\":null,\"junction\":null,\"key\":null,\"operation\":\"select\",\"order_by\":null,\"primary_table\":null,\"returning\":null,\"role_col\":null,\"role_table\":null,\"schema\":\"ob-poc\",\"set_values\":null,\"table\":\"v_documents_with_status\",\"to_col\":null,\"type_code\":null,\"type_id_column\":null}"
)

(utterance-binding kyc.list-missing-items :phrases ["what information is still missing before KYC sign-off?" "missing kyc information" "information missing before sign-off" "what is still missing before KYC sign-off" "missing kyc items"] :domain "kyc" :verb kyc.list-missing-items)

(verb kyc.read-case
  :domain "kyc"
  :description "Read case details"
  :behavior "crud"
  :effect-class "read_snapshot"
  :flavour "attribute_mutating"
  :metadata-json "{\"action_class\":null,\"dangerous\":false,\"harm_class\":null,\"internal\":false,\"noun\":\"kyc_case\",\"phase_tags\":[\"kyc\"],\"produces_focus\":false,\"removal_version\":null,\"replaced_by\":null,\"replaces\":null,\"requires_subject\":true,\"scope\":\"cbu\",\"side_effects\":\"facts_only\",\"since_version\":null,\"source_of_truth\":\"workflow\",\"status\":\"active\",\"subject_kinds\":[],\"tags\":[\"kyc\"],\"tier\":\"reference\",\"writes_operational\":false}"
  :three-axis-json "{\"consequence\":{\"baseline\":\"benign\",\"escalation\":[]},\"external_effects\":[],\"state_effect\":\"preserving\"}"
  :returns-json "{\"capture\":null,\"name\":null,\"type\":\"record_set\"}"
  :args-json "[{\"default\":null,\"description\":null,\"fuzzy_check\":null,\"lookup\":null,\"maps_to\":\"case_id\",\"name\":\"case-id\",\"preferred_roles\":[],\"required\":false,\"slot_type\":null,\"type\":\"uuid\",\"valid_values\":null,\"validation\":null}]"
  :crud-json "{\"base_table\":null,\"conflict_constraint\":null,\"conflict_keys\":null,\"extension_table\":null,\"extension_table_column\":null,\"filter_col\":null,\"fk_col\":null,\"from_col\":null,\"join_col\":null,\"join_table\":null,\"junction\":null,\"key\":null,\"operation\":\"select\",\"order_by\":null,\"primary_table\":null,\"returning\":null,\"role_col\":null,\"role_table\":null,\"schema\":\"ob-poc\",\"set_values\":null,\"table\":\"cases\",\"to_col\":null,\"type_code\":null,\"type_id_column\":null}"
)

(utterance-binding kyc.read-case :phrases ["read case" "get case details" "show case" "view case"] :domain "kyc" :verb kyc.read-case)
